In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import loadtxt
%matplotlib inline

In [30]:
#Read Bulk Data file
#singleCellDF = pd.read_csv('final_single_cell_data.txt', sep='\t',header=None)
fullBulkData = pd.read_csv('TCGA_BRCA_dat.txt', sep='\t')

In [31]:
fullBulkData.head()

,A1BG|1,A2M|2,NAT1|9,NAT2|10,SERPINA3|12,SERPINA3|12.1,AADAC|13,AAMP|14,AANAT|15,AARS|16,...,FRG2C|100288801,ZNF605|100289635,NHEG1|100294720,LOC100302401|100302401,LOC100302640|100302640,NCRNA00182|100302692,TMED7-TICAM2|100302736,TMED7-TICAM2|100302736.1,TMED7-TICAM2|100302736.2,LOC100303728|100303728
TCGA-3C-AAAU,571.84,16823.52,23254,31,49565.0,49565.0,0,5957,1,12794,...,0,1724,1,22.00,53,124,168.68,168.68,168.68,135
TCGA-3C-AALI,436.55,13924.87,1051,157,244.0,244.0,2,5480,4,8406,...,1,346,0,50.12,2,40,76.09,76.09,76.09,30
TCGA-3C-AALJ,466.83,9750.96,1330,1,11712.0,11712.0,1,2528,2,2820,...,0,603,0,10.00,2,48,0.00,0.00,0.00,12
TCGA-3C-AALK,461.69,26490.85,2786,22,32425.0,32425.0,7,6677,1,5131,...,2,995,0,39.20,16,97,160.33,160.33,160.33,53
TCGA-4H-AAAK,631.87,22525.79,307,2,24231.0,24231.0,1,7733,1,5548,...,1,1026,0,66.25,5,113,271.66,271.66,271.66,44

In [32]:
fullGeneNames = list(fullBulkData.columns.values)

In [33]:
#Preprocess the gene names to ignore stuff after '|'
geneNames = []
for gene in fullGeneNames:
    for i in range(len(gene)):
        if gene[i]=='|':
            pos = i
            geneNames.append(gene[0:pos])
            break

In [34]:
#singleCellDF = singleCellDF[1:] #take the data less the header row
fullBulkData.columns = geneNames #set the header row as the df header

In [35]:
fullBulkData.head()

,A1BG,A2M,NAT1,NAT2,SERPINA3,SERPINA3,AADAC,AAMP,AANAT,AARS,...,FRG2C,ZNF605,NHEG1,LOC100302401,LOC100302640,NCRNA00182,TMED7-TICAM2,TMED7-TICAM2,TMED7-TICAM2,LOC100303728
TCGA-3C-AAAU,571.84,16823.52,23254,31,49565.0,49565.0,0,5957,1,12794,...,0,1724,1,22.00,53,124,168.68,168.68,168.68,135
TCGA-3C-AALI,436.55,13924.87,1051,157,244.0,244.0,2,5480,4,8406,...,1,346,0,50.12,2,40,76.09,76.09,76.09,30
TCGA-3C-AALJ,466.83,9750.96,1330,1,11712.0,11712.0,1,2528,2,2820,...,0,603,0,10.00,2,48,0.00,0.00,0.00,12
TCGA-3C-AALK,461.69,26490.85,2786,22,32425.0,32425.0,7,6677,1,5131,...,2,995,0,39.20,16,97,160.33,160.33,160.33,53
TCGA-4H-AAAK,631.87,22525.79,307,2,24231.0,24231.0,1,7733,1,5548,...,1,1026,0,66.25,5,113,271.66,271.66,271.66,44

In [36]:
#Convert FPKM to TPM
fullBulkData = fullBulkData.apply(lambda x: x*1000000/sum(x))

In [37]:
fullBulkData.head()

,A1BG,A2M,NAT1,NAT2,SERPINA3,SERPINA3,AADAC,AAMP,AANAT,AARS,...,FRG2C,ZNF605,NHEG1,LOC100302401,LOC100302640,NCRNA00182,TMED7-TICAM2,TMED7-TICAM2,TMED7-TICAM2,LOC100303728
TCGA-3C-AAAU,1070.184562,355.096192,2580.560392,512.540714,780.592391,780.592391,0.000000,804.108960,704.225352,1282.559714,...,0.000000,1119.562669,1883.239171,428.115430,3600.054340,1038.212934,499.375913,499.375913,499.375913,1578.356638
TCGA-3C-AALI,816.992638,293.914015,116.632363,2595.770712,3.842723,3.842723,69.058389,739.720850,2816.901408,842.676017,...,196.463654,224.691812,0.000000,975.324789,135.851107,334.907398,225.263892,225.263892,225.263892,350.745920
TCGA-3C-AALJ,873.660917,205.814762,147.593761,16.533571,184.450683,184.450683,34.529194,341.243487,1408.450704,282.696451,...,0.000000,391.587175,0.000000,194.597923,135.851107,401.888878,0.000000,0.000000,0.000000,140.298368
TCGA-3C-AALK,864.041533,559.145764,309.170089,363.738571,510.656880,510.656880,241.704361,901.298561,704.225352,514.367195,...,392.927308,646.151309,0.000000,762.823857,1086.808857,812.150440,474.655799,474.655799,474.655799,619.651125
TCGA-4H-AAAK,1182.529237,475.454735,34.068635,33.067143,381.610698,381.610698,34.529194,1043.843309,704.225352,556.170181,...,196.463654,666.282656,0.000000,1289.211238,339.627768,946.113400,804.247454,804.247454,804.247454,514.427349

In [38]:
#Apply log2(TPM + 1)
fullBulkData = fullBulkData.apply(lambda x: np.log2(x+1))

In [39]:
fullBulkData.head()

,A1BG,A2M,NAT1,NAT2,SERPINA3,SERPINA3,AADAC,AAMP,AANAT,AARS,...,FRG2C,ZNF605,NHEG1,LOC100302401,LOC100302640,NCRNA00182,TMED7-TICAM2,TMED7-TICAM2,TMED7-TICAM2,LOC100303728
TCGA-3C-AAAU,10.064991,8.476123,11.334028,9.004335,9.610273,9.610273,0.000000,9.653040,9.461941,10.325935,...,0.000000,10.130008,10.879766,8.745222,11.814204,10.021276,8.966869,8.966869,8.966869,10.625121
TCGA-3C-AALI,9.675944,8.204151,6.878141,11.342503,2.275818,2.275818,6.130486,9.532786,11.460405,9.720545,...,7.625443,7.818210,0.000000,9.931217,7.096463,8.391920,7.821863,7.821863,7.821863,8.458390
TCGA-3C-AALJ,9.772580,7.692195,7.215230,4.132048,7.534892,7.534892,5.150933,8.418879,10.460917,8.148204,...,0.000000,8.616869,0.000000,7.611747,7.096463,8.654238,0.000000,0.000000,0.000000,7.142601
TCGA-3C-AALK,9.756626,9.129658,8.276916,8.510719,8.999033,8.999033,7.923056,9.817461,9.461941,9.009457,...,8.621786,9.337959,0.000000,9.577096,10.087209,9.667378,8.893774,8.893774,8.893774,9.277639
TCGA-4H-AAAK,10.208880,8.896195,5.132109,5.090309,8.579733,8.579733,5.150933,10.029071,9.461941,9.121974,...,7.625443,9.382154,0.000000,10.333392,8.412052,9.887393,9.653288,9.653288,9.653288,9.009625

In [42]:
bulkData = fullBulkData.transpose()

In [43]:
bulkData.head()

,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,TCGA-A1-A0SD,...,TCGA-UL-AAZ6,TCGA-UU-A93S,TCGA-V7-A7HQ,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6
A1BG,10.064991,9.675944,9.772580,9.756626,10.208880,9.346765,8.925402,10.136008,7.682179,9.654596,...,7.700337,9.703472,11.615322,11.038146,8.156410,10.081980,10.052689,9.982739,10.428511,10.384288
A2M,8.476123,8.204151,7.692195,9.129658,8.896195,8.796722,8.643884,7.016084,10.534111,10.568965,...,7.945639,6.700180,8.113517,9.672359,8.008000,7.141375,10.092677,9.579056,10.347338,8.801447
NAT1,11.334028,6.878141,7.215230,8.276916,5.132109,7.195704,8.421207,7.562997,3.936919,9.266032,...,4.811335,3.817090,5.291848,10.001019,5.889004,8.972621,6.080969,8.356737,9.145410,9.405001
NAT2,9.004335,11.342503,4.132048,8.510719,5.090309,8.443793,6.068978,6.867093,5.661086,8.694669,...,6.068978,9.803829,8.373611,9.572784,8.443793,10.491273,7.226914,13.856388,7.860901,7.226914
SERPINA3,9.610273,2.275818,7.534892,8.999033,8.579733,8.775045,5.266713,4.764187,6.742392,11.726780,...,8.872406,3.396168,8.652286,9.074470,5.091207,8.335818,9.516412,10.272908,10.710089,10.799517

In [45]:
#Save the bulk data file
bulkData.to_csv('bulk_data.txt', sep='\t')

In [47]:
bulkData.shape

(21022, 1094)