In [147]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import loadtxt
%matplotlib inline

In [148]:
clinicalDataDF = pd.read_csv('TCGA_clincical_BRCA.txt', sep='\t')

In [149]:
clinicalDataDF.head()

,CASE_ID,AGE,AJCC_METASTASIS_PATHOLOGIC_PM,AJCC_NODES_PATHOLOGIC_PN,AJCC_PATHOLOGIC_TUMOR_STAGE,AJCC_STAGING_EDITION,AJCC_TUMOR_PATHOLOGIC_PT,BRACHYTHERAPY_TOTAL_DOSE_POINT_A,CANCER_TYPE,CANCER_TYPE_DETAILED,...,STAGING_SYSTEM,STAGING_SYSTEM_OTHER,SURGERY_FOR_POSITIVE_MARGINS,SURGERY_FOR_POSITIVE_MARGINS_OTHER,SURGICAL_PROCEDURE_FIRST,TISSUE_SOURCE_SITE,TUMOR_STATUS,TUMOR_TISSUE_SITE,VIAL_NUMBER,VITAL_STATUS
0,TCGA-A7-A3J0-01,62.0,M0,N0,Stage IIA,7th,T2,NaN,Breast Cancer,Breast Invasive Mixed Mucinous Carcinoma,...,Sentinel node biopsy alone,NaN,NaN,NaN,Lumpectomy,A7,TUMOR FREE,Breast,A,Alive
1,TCGA-OL-A66N-01,59.0,MX,N3,Stage IIIC,7th,T3,NaN,Breast Cancer,Breast Invasive Lobular Carcinoma,...,Sentinel node biopsy alone,NaN,NaN,NaN,Modified Radical Mastectomy,OL,TUMOR FREE,Breast,A,Alive
2,TCGA-AQ-A0Y5-01,70.0,MX,N2a,Stage IIIA,7th,T2,NaN,Breast Cancer,Breast Invasive Ductal Carcinoma,...,Sentinel lymph node biopsy plus axillary disse...,NaN,NaN,NaN,Modified Radical Mastectomy,AQ,TUMOR FREE,Breast,A,Dead
3,TCGA-E9-A22H-01,42.0,M0,N1,Stage IIB,7th,T2,NaN,Breast Cancer,Breast Invasive Ductal Carcinoma,...,Axillary lymph node dissection alone,NaN,NaN,NaN,Modified Radical Mastectomy,E9,TUMOR FREE,Breast,A,Alive
4,TCGA-BH-A0EB-01,69.0,M0,N0 (i-),Stage IA,NaN,T1c,H-SCORE 300,Breast Cancer,Breast Invasive Ductal Carcinoma,...,Sentinel lymph node biopsy plus axillary disse...,NaN,NaN,NaN,Other,BH,TUMOR FREE,Breast,A,Alive

In [150]:
clinicalDataDF['IHC_HER2'].head()

0     Negative
1          NaN
2     Positive
3     Positive
4    Equivocal
Name: IHC_HER2, dtype: object

In [151]:
clinicalDataDF = clinicalDataDF.loc[clinicalDataDF['IHC_HER2'] == 'Positive']

In [152]:
def removeLastHyphenOnwards(x):
    for i in range(len(x)-1,0,-1):
        if x[i]=='-':
            return x[0:i]

In [153]:
clinicalDataDF['CASE_ID'] = clinicalDataDF['CASE_ID'].apply(lambda x: removeLastHyphenOnwards(x))

In [154]:
clinicalDataDF.shape

(164, 108)

In [155]:
bdDataDF = pd.read_csv('1094_bulk_data.txt', sep='\t')

In [156]:
bdDataDF.shape

(421, 1095)

In [157]:
bdDataDF.head()

,gene_name,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,...,TCGA-UL-AAZ6,TCGA-UU-A93S,TCGA-V7-A7HQ,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6
0,ACACB,9.133498,6.342497,6.933454,7.165672,8.210531,8.176793,6.938200,11.197878,8.081337,...,7.815933,4.887319,8.268209,9.260193,9.957976,7.209516,10.890561,10.705308,7.711690,7.217347
1,ADARB1,9.950973,8.154415,7.585128,10.107984,10.016327,9.685011,7.803326,8.078978,9.855646,...,9.934803,6.234935,8.944801,9.758415,8.223302,8.382373,9.744811,10.163086,9.501889,9.301419
2,ADCY1,14.324604,5.724666,7.828702,8.492381,6.158429,6.216949,5.424067,5.545286,5.960905,...,10.400067,2.732277,8.543166,8.104271,4.228168,4.959161,8.367606,9.791481,5.641652,10.737143
3,ADCYAP1,9.761663,6.255447,4.561885,6.105541,8.618625,6.515331,7.622291,4.007144,6.735468,...,8.824586,0.000000,6.105541,7.507423,7.779074,0.000000,10.683572,7.507423,9.408488,7.245974
4,AES,9.896728,9.825457,9.095660,10.474256,9.186910,9.791401,9.181365,9.740006,9.686296,...,10.526041,10.261424,10.406455,10.574997,9.547935,9.534210,9.752073,9.305309,10.024375,10.468843

In [158]:
bulkDataDF = bdDataDF.transpose()

In [159]:
bulkDataDF.head()

,0,1,2,3,4,5,6,7,8,9,...,411,412,413,414,415,416,417,418,419,420
gene_name,ACACB,ADARB1,ADCY1,ADCYAP1,AES,NR0B1,ALDH1B1,ALPL,ANK1,APBA2,...,TXNDC17,LRP5L,OSBPL10,KIR3DL3,LPCAT4,SGMS1,H19,FRYL,MSL1,ZNF710
TCGA-3C-AAAU,9.1335,9.95097,14.3246,9.76166,9.89673,4.78084,9.12618,6.56801,11.9047,11.8943,...,9.75254,9.91976,8.11641,0,10.0911,8.71871,7.34243,9.8581,9.79123,10.7253
TCGA-3C-AALI,6.3425,8.15441,5.72467,6.25545,9.82546,0,8.9149,9.7319,6.29668,9.3948,...,9.35455,9.68794,8.68701,0,8.44922,7.8782,8.76258,8.3394,8.10807,9.59206
TCGA-3C-AALJ,6.93345,7.58513,7.8287,4.56188,9.09566,0,8.49056,8.13902,5.05911,9.96324,...,8.49966,8.26674,7.10903,0,9.10531,7.49634,9.34448,7.59315,8.9288,8.24777
TCGA-3C-AALK,7.16567,10.108,8.49238,6.10554,10.4743,0,9.78557,9.68084,6.21529,9.77885,...,9.61329,9.56009,9.35235,0,9.5414,9.56897,8.61787,9.03278,10.1679,9.74595

In [160]:
new_header = bulkDataDF.iloc[0] #grab the first row for the header
bulkDataDF = bulkDataDF[1:] #take the data less the header row
bulkDataDF.columns = new_header #set the header row as the df header

In [161]:
bulkDataDF.head()

gene_name,ACACB,ADARB1,ADCY1,ADCYAP1,AES,NR0B1,ALDH1B1,ALPL,ANK1,APBA2,...,TXNDC17,LRP5L,OSBPL10,KIR3DL3,LPCAT4,SGMS1,H19,FRYL,MSL1,ZNF710
TCGA-3C-AAAU,9.1335,9.95097,14.3246,9.76166,9.89673,4.78084,9.12618,6.56801,11.9047,11.8943,...,9.75254,9.91976,8.11641,0,10.0911,8.71871,7.34243,9.8581,9.79123,10.7253
TCGA-3C-AALI,6.3425,8.15441,5.72467,6.25545,9.82546,0,8.9149,9.7319,6.29668,9.3948,...,9.35455,9.68794,8.68701,0,8.44922,7.8782,8.76258,8.3394,8.10807,9.59206
TCGA-3C-AALJ,6.93345,7.58513,7.8287,4.56188,9.09566,0,8.49056,8.13902,5.05911,9.96324,...,8.49966,8.26674,7.10903,0,9.10531,7.49634,9.34448,7.59315,8.9288,8.24777
TCGA-3C-AALK,7.16567,10.108,8.49238,6.10554,10.4743,0,9.78557,9.68084,6.21529,9.77885,...,9.61329,9.56009,9.35235,0,9.5414,9.56897,8.61787,9.03278,10.1679,9.74595
TCGA-4H-AAAK,8.21053,10.0163,6.15843,8.61862,9.18691,6.74093,10.0773,7.32128,4.96266,10.0948,...,8.97666,9.81162,9.21254,0,10.201,9.22491,9.48604,8.95979,9.32874,9.7309

In [162]:
#bulkDataDF = bulkDataDF.rename(index=str, columns={'gene_name': "CASE_ID"})

In [163]:
bulkDataDF['CASE_ID'] = bulkDataDF.index

In [164]:
bulkDataDF.head()

gene_name,ACACB,ADARB1,ADCY1,ADCYAP1,AES,NR0B1,ALDH1B1,ALPL,ANK1,APBA2,...,LRP5L,OSBPL10,KIR3DL3,LPCAT4,SGMS1,H19,FRYL,MSL1,ZNF710,CASE_ID
TCGA-3C-AAAU,9.1335,9.95097,14.3246,9.76166,9.89673,4.78084,9.12618,6.56801,11.9047,11.8943,...,9.91976,8.11641,0,10.0911,8.71871,7.34243,9.8581,9.79123,10.7253,TCGA-3C-AAAU
TCGA-3C-AALI,6.3425,8.15441,5.72467,6.25545,9.82546,0,8.9149,9.7319,6.29668,9.3948,...,9.68794,8.68701,0,8.44922,7.8782,8.76258,8.3394,8.10807,9.59206,TCGA-3C-AALI
TCGA-3C-AALJ,6.93345,7.58513,7.8287,4.56188,9.09566,0,8.49056,8.13902,5.05911,9.96324,...,8.26674,7.10903,0,9.10531,7.49634,9.34448,7.59315,8.9288,8.24777,TCGA-3C-AALJ
TCGA-3C-AALK,7.16567,10.108,8.49238,6.10554,10.4743,0,9.78557,9.68084,6.21529,9.77885,...,9.56009,9.35235,0,9.5414,9.56897,8.61787,9.03278,10.1679,9.74595,TCGA-3C-AALK
TCGA-4H-AAAK,8.21053,10.0163,6.15843,8.61862,9.18691,6.74093,10.0773,7.32128,4.96266,10.0948,...,9.81162,9.21254,0,10.201,9.22491,9.48604,8.95979,9.32874,9.7309,TCGA-4H-AAAK

In [165]:
joined_df = bulkDataDF.merge(clinicalDataDF, on='CASE_ID', how='inner')

In [166]:
joined_df.shape

(164, 529)

In [167]:
joined_df.head()

,ACACB,ADARB1,ADCY1,ADCYAP1,AES,NR0B1,ALDH1B1,ALPL,ANK1,APBA2,...,STAGING_SYSTEM,STAGING_SYSTEM_OTHER,SURGERY_FOR_POSITIVE_MARGINS,SURGERY_FOR_POSITIVE_MARGINS_OTHER,SURGICAL_PROCEDURE_FIRST,TISSUE_SOURCE_SITE,TUMOR_STATUS,TUMOR_TISSUE_SITE,VIAL_NUMBER,VITAL_STATUS
0,6.3425,8.15441,5.72467,6.25545,9.82546,0,8.9149,9.7319,6.29668,9.3948,...,Sentinel lymph node biopsy plus axillary disse...,NaN,NaN,NaN,Lumpectomy,3C,TUMOR FREE,Breast,A,Alive
1,7.16567,10.108,8.49238,6.10554,10.4743,0,9.78557,9.68084,6.21529,9.77885,...,Sentinel node biopsy alone,NaN,NaN,NaN,Simple Mastectomy,3C,TUMOR FREE,Breast,A,Alive
2,7.72823,10.1193,6.05723,6.51533,9.91824,0,10.7828,9.11546,6.97776,10.9122,...,Sentinel lymph node biopsy plus axillary disse...,NaN,NaN,NaN,Modified Radical Mastectomy,A1,TUMOR FREE,Breast,A,Alive
3,7.50651,9.77667,10.4338,8.31138,9.85732,0,10.3161,8.38215,5.93934,9.87211,...,Sentinel lymph node biopsy plus axillary disse...,NaN,NaN,NaN,Lumpectomy,A1,TUMOR FREE,Breast,A,Alive
4,6.57966,8.13369,4.88235,6.8341,9.54242,0,10.2979,11.017,5.77866,9.85698,...,Axillary lymph node dissection alone,NaN,NaN,NaN,Modified Radical Mastectomy,A2,TUMOR FREE,Breast,A,Alive

In [168]:
tmpBulkData = joined_df.loc[:,'ACACB':'CASE_ID']

In [169]:
tmpBulkData.shape

(164, 422)

In [170]:
tmpBulkData.head()

,ACACB,ADARB1,ADCY1,ADCYAP1,AES,NR0B1,ALDH1B1,ALPL,ANK1,APBA2,...,LRP5L,OSBPL10,KIR3DL3,LPCAT4,SGMS1,H19,FRYL,MSL1,ZNF710,CASE_ID
0,6.3425,8.15441,5.72467,6.25545,9.82546,0,8.9149,9.7319,6.29668,9.3948,...,9.68794,8.68701,0,8.44922,7.8782,8.76258,8.3394,8.10807,9.59206,TCGA-3C-AALI
1,7.16567,10.108,8.49238,6.10554,10.4743,0,9.78557,9.68084,6.21529,9.77885,...,9.56009,9.35235,0,9.5414,9.56897,8.61787,9.03278,10.1679,9.74595,TCGA-3C-AALK
2,7.72823,10.1193,6.05723,6.51533,9.91824,0,10.7828,9.11546,6.97776,10.9122,...,8.8802,10.1211,0,9.56963,10.569,11.0521,9.35693,12.6882,10.5901,TCGA-A1-A0SM
3,7.50651,9.77667,10.4338,8.31138,9.85732,0,10.3161,8.38215,5.93934,9.87211,...,8.13334,9.93168,0,9.34196,9.66314,10.1198,9.50049,13.1729,11.0103,TCGA-A1-A0SN
4,6.57966,8.13369,4.88235,6.8341,9.54242,0,10.2979,11.017,5.77866,9.85698,...,9.00547,9.30357,0,8.86221,9.04098,10.3571,7.85352,11.0858,9.35498,TCGA-A2-A04W

In [171]:
tmpClinicalData = joined_df.loc[:,'CASE_ID':'VITAL_STATUS']

In [172]:
tmpClinicalData.head()

,CASE_ID,AGE,AJCC_METASTASIS_PATHOLOGIC_PM,AJCC_NODES_PATHOLOGIC_PN,AJCC_PATHOLOGIC_TUMOR_STAGE,AJCC_STAGING_EDITION,AJCC_TUMOR_PATHOLOGIC_PT,BRACHYTHERAPY_TOTAL_DOSE_POINT_A,CANCER_TYPE,CANCER_TYPE_DETAILED,...,STAGING_SYSTEM,STAGING_SYSTEM_OTHER,SURGERY_FOR_POSITIVE_MARGINS,SURGERY_FOR_POSITIVE_MARGINS_OTHER,SURGICAL_PROCEDURE_FIRST,TISSUE_SOURCE_SITE,TUMOR_STATUS,TUMOR_TISSUE_SITE,VIAL_NUMBER,VITAL_STATUS
0,TCGA-3C-AALI,50.0,M0,N1a,Stage IIB,6th,T2,NaN,Breast Cancer,Breast Invasive Ductal Carcinoma,...,Sentinel lymph node biopsy plus axillary disse...,NaN,NaN,NaN,Lumpectomy,3C,TUMOR FREE,Breast,A,Alive
1,TCGA-3C-AALK,52.0,M0,N0 (i+),Stage IA,7th,T1c,NaN,Breast Cancer,Breast Invasive Ductal Carcinoma,...,Sentinel node biopsy alone,NaN,NaN,NaN,Simple Mastectomy,3C,TUMOR FREE,Breast,A,Alive
2,TCGA-A1-A0SM,77.0,M0,N0 (i-),Stage IIA,6th,T2,NaN,Breast Cancer,Breast Invasive Ductal Carcinoma,...,Sentinel lymph node biopsy plus axillary disse...,NaN,NaN,NaN,Modified Radical Mastectomy,A1,TUMOR FREE,Breast,A,Alive
3,TCGA-A1-A0SN,50.0,MX,N1,Stage IIA,6th,T1c,NaN,Breast Cancer,Breast Invasive Ductal Carcinoma,...,Sentinel lymph node biopsy plus axillary disse...,NaN,NaN,NaN,Lumpectomy,A1,TUMOR FREE,Breast,A,Alive
4,TCGA-A2-A04W,50.0,M0,N1mi,Stage IIB,6th,T2,NaN,Breast Cancer,Breast Invasive Ductal Carcinoma,...,Axillary lymph node dissection alone,NaN,NaN,NaN,Modified Radical Mastectomy,A2,TUMOR FREE,Breast,A,Alive

In [182]:
mid = tmpBulkData['CASE_ID']
tmpBulkData.drop(labels=['CASE_ID'], axis=1,inplace = True)
tmpBulkData.insert(0, 'CASE_ID', mid)

In [183]:
tmpBulkData.head()

,CASE_ID,ACACB,ADARB1,ADCY1,ADCYAP1,AES,NR0B1,ALDH1B1,ALPL,ANK1,...,TXNDC17,LRP5L,OSBPL10,KIR3DL3,LPCAT4,SGMS1,H19,FRYL,MSL1,ZNF710
0,TCGA-3C-AALI,6.3425,8.15441,5.72467,6.25545,9.82546,0,8.9149,9.7319,6.29668,...,9.35455,9.68794,8.68701,0,8.44922,7.8782,8.76258,8.3394,8.10807,9.59206
1,TCGA-3C-AALK,7.16567,10.108,8.49238,6.10554,10.4743,0,9.78557,9.68084,6.21529,...,9.61329,9.56009,9.35235,0,9.5414,9.56897,8.61787,9.03278,10.1679,9.74595
2,TCGA-A1-A0SM,7.72823,10.1193,6.05723,6.51533,9.91824,0,10.7828,9.11546,6.97776,...,10.8923,8.8802,10.1211,0,9.56963,10.569,11.0521,9.35693,12.6882,10.5901
3,TCGA-A1-A0SN,7.50651,9.77667,10.4338,8.31138,9.85732,0,10.3161,8.38215,5.93934,...,9.78632,8.13334,9.93168,0,9.34196,9.66314,10.1198,9.50049,13.1729,11.0103
4,TCGA-A2-A04W,6.57966,8.13369,4.88235,6.8341,9.54242,0,10.2979,11.017,5.77866,...,10.6915,9.00547,9.30357,0,8.86221,9.04098,10.3571,7.85352,11.0858,9.35498

In [184]:
tmpBulkData.shape

(164, 422)

In [185]:
tmpBulkData.head()

,CASE_ID,ACACB,ADARB1,ADCY1,ADCYAP1,AES,NR0B1,ALDH1B1,ALPL,ANK1,...,TXNDC17,LRP5L,OSBPL10,KIR3DL3,LPCAT4,SGMS1,H19,FRYL,MSL1,ZNF710
0,TCGA-3C-AALI,6.3425,8.15441,5.72467,6.25545,9.82546,0,8.9149,9.7319,6.29668,...,9.35455,9.68794,8.68701,0,8.44922,7.8782,8.76258,8.3394,8.10807,9.59206
1,TCGA-3C-AALK,7.16567,10.108,8.49238,6.10554,10.4743,0,9.78557,9.68084,6.21529,...,9.61329,9.56009,9.35235,0,9.5414,9.56897,8.61787,9.03278,10.1679,9.74595
2,TCGA-A1-A0SM,7.72823,10.1193,6.05723,6.51533,9.91824,0,10.7828,9.11546,6.97776,...,10.8923,8.8802,10.1211,0,9.56963,10.569,11.0521,9.35693,12.6882,10.5901
3,TCGA-A1-A0SN,7.50651,9.77667,10.4338,8.31138,9.85732,0,10.3161,8.38215,5.93934,...,9.78632,8.13334,9.93168,0,9.34196,9.66314,10.1198,9.50049,13.1729,11.0103
4,TCGA-A2-A04W,6.57966,8.13369,4.88235,6.8341,9.54242,0,10.2979,11.017,5.77866,...,10.6915,9.00547,9.30357,0,8.86221,9.04098,10.3571,7.85352,11.0858,9.35498

In [186]:
finalBulkDataDF = tmpBulkData.transpose()

In [187]:
finalBulkDataDF.head()

,0,1,2,3,4,5,6,7,8,9,...,154,155,156,157,158,159,160,161,162,163
CASE_ID,TCGA-3C-AALI,TCGA-3C-AALK,TCGA-A1-A0SM,TCGA-A1-A0SN,TCGA-A2-A04W,TCGA-A2-A04X,TCGA-A2-A0CX,TCGA-A2-A0D1,TCGA-A2-A0EQ,TCGA-A2-A0EY,...,TCGA-JL-A3YX,TCGA-LD-A9QF,TCGA-LL-A5YL,TCGA-LL-A7T0,TCGA-LL-A9Q3,TCGA-PE-A5DC,TCGA-PE-A5DD,TCGA-S3-AA14,TCGA-UL-AAZ6,TCGA-UU-A93S
ACACB,6.3425,7.16567,7.72823,7.50651,6.57966,6.99852,8.35418,6.3281,7.80038,7.32636,...,9.213,8.62533,8.67451,6.87029,10.5052,9.88488,9.61241,8.46685,7.81593,4.88732
ADARB1,8.15441,10.108,10.1193,9.77667,8.13369,9.20252,10.1201,9.30407,9.98029,10.4298,...,9.51225,9.65312,8.4888,9.10853,8.53695,9.28406,9.72317,9.75066,9.9348,6.23493
ADCY1,5.72467,8.49238,6.05723,10.4338,4.88235,4.16471,5.72467,6.57926,6.7439,8.56073,...,9.98338,5.19975,6.87853,6.33214,8.45971,6.95241,7.72254,8.7182,10.4001,2.73228
ADCYAP1,6.25545,6.10554,6.51533,8.31138,6.8341,9.72357,4.00714,12.3946,9.50146,7.24597,...,11.07,8.27672,8.31138,4.56188,9.35965,8.80039,0,5.74894,8.82459,0

In [188]:
new_header = finalBulkDataDF.iloc[0] #grab the first row for the header
finalBulkDataDF = finalBulkDataDF[1:] #take the data less the header row
finalBulkDataDF.columns = new_header #set the header row as the df header

In [189]:
finalBulkDataDF.head()

CASE_ID,TCGA-3C-AALI,TCGA-3C-AALK,TCGA-A1-A0SM,TCGA-A1-A0SN,TCGA-A2-A04W,TCGA-A2-A04X,TCGA-A2-A0CX,TCGA-A2-A0D1,TCGA-A2-A0EQ,TCGA-A2-A0EY,...,TCGA-JL-A3YX,TCGA-LD-A9QF,TCGA-LL-A5YL,TCGA-LL-A7T0,TCGA-LL-A9Q3,TCGA-PE-A5DC,TCGA-PE-A5DD,TCGA-S3-AA14,TCGA-UL-AAZ6,TCGA-UU-A93S
ACACB,6.3425,7.16567,7.72823,7.50651,6.57966,6.99852,8.35418,6.3281,7.80038,7.32636,...,9.213,8.62533,8.67451,6.87029,10.5052,9.88488,9.61241,8.46685,7.81593,4.88732
ADARB1,8.15441,10.108,10.1193,9.77667,8.13369,9.20252,10.1201,9.30407,9.98029,10.4298,...,9.51225,9.65312,8.4888,9.10853,8.53695,9.28406,9.72317,9.75066,9.9348,6.23493
ADCY1,5.72467,8.49238,6.05723,10.4338,4.88235,4.16471,5.72467,6.57926,6.7439,8.56073,...,9.98338,5.19975,6.87853,6.33214,8.45971,6.95241,7.72254,8.7182,10.4001,2.73228
ADCYAP1,6.25545,6.10554,6.51533,8.31138,6.8341,9.72357,4.00714,12.3946,9.50146,7.24597,...,11.07,8.27672,8.31138,4.56188,9.35965,8.80039,0,5.74894,8.82459,0
AES,9.82546,10.4743,9.91824,9.85732,9.54242,10.0627,9.33303,10.7692,10.6025,10.5146,...,10.5633,9.74889,10.2448,10.0001,11.2362,10.0341,9.68229,9.24087,10.526,10.2614

In [190]:
finalBulkDataDF.to_csv('164_bulk_data.txt', sep='\t')

In [191]:
tmpDF = pd.read_csv('164_bulk_data.txt', sep='\t')

In [192]:
tmpDF.head()

,Unnamed: 0,TCGA-3C-AALI,TCGA-3C-AALK,TCGA-A1-A0SM,TCGA-A1-A0SN,TCGA-A2-A04W,TCGA-A2-A04X,TCGA-A2-A0CX,TCGA-A2-A0D1,TCGA-A2-A0EQ,...,TCGA-JL-A3YX,TCGA-LD-A9QF,TCGA-LL-A5YL,TCGA-LL-A7T0,TCGA-LL-A9Q3,TCGA-PE-A5DC,TCGA-PE-A5DD,TCGA-S3-AA14,TCGA-UL-AAZ6,TCGA-UU-A93S
0,ACACB,6.342497,7.165672,7.728226,7.506511,6.579663,6.998518,8.354177,6.328104,7.800378,...,9.212998,8.625332,8.674512,6.870292,10.505160,9.884882,9.612412,8.466854,7.815933,4.887319
1,ADARB1,8.154415,10.107984,10.119325,9.776675,8.133687,9.202521,10.120077,9.304072,9.980293,...,9.512250,9.653115,8.488800,9.108532,8.536954,9.284057,9.723171,9.750657,9.934803,6.234935
2,ADCY1,5.724666,8.492381,6.057233,10.433823,4.882349,4.164715,5.724666,6.579264,6.743898,...,9.983376,5.199747,6.878530,6.332138,8.459708,6.952412,7.722537,8.718197,10.400067,2.732277
3,ADCYAP1,6.255447,6.105541,6.515331,8.311376,6.834101,9.723572,4.007144,12.394558,9.501464,...,11.069999,8.276722,8.311376,4.561885,9.359651,8.800393,0.000000,5.748944,8.824586,0.000000
4,AES,9.825457,10.474256,9.918235,9.857322,9.542424,10.062736,9.333025,10.769199,10.602490,...,10.563344,9.748886,10.244780,10.000122,11.236185,10.034094,9.682293,9.240873,10.526041,10.261424

In [193]:
tmpDF = tmpDF.rename(index=str, columns={'Unnamed: 0': "gene_name"})

In [194]:
tmpDF.head()

,gene_name,TCGA-3C-AALI,TCGA-3C-AALK,TCGA-A1-A0SM,TCGA-A1-A0SN,TCGA-A2-A04W,TCGA-A2-A04X,TCGA-A2-A0CX,TCGA-A2-A0D1,TCGA-A2-A0EQ,...,TCGA-JL-A3YX,TCGA-LD-A9QF,TCGA-LL-A5YL,TCGA-LL-A7T0,TCGA-LL-A9Q3,TCGA-PE-A5DC,TCGA-PE-A5DD,TCGA-S3-AA14,TCGA-UL-AAZ6,TCGA-UU-A93S
0,ACACB,6.342497,7.165672,7.728226,7.506511,6.579663,6.998518,8.354177,6.328104,7.800378,...,9.212998,8.625332,8.674512,6.870292,10.505160,9.884882,9.612412,8.466854,7.815933,4.887319
1,ADARB1,8.154415,10.107984,10.119325,9.776675,8.133687,9.202521,10.120077,9.304072,9.980293,...,9.512250,9.653115,8.488800,9.108532,8.536954,9.284057,9.723171,9.750657,9.934803,6.234935
2,ADCY1,5.724666,8.492381,6.057233,10.433823,4.882349,4.164715,5.724666,6.579264,6.743898,...,9.983376,5.199747,6.878530,6.332138,8.459708,6.952412,7.722537,8.718197,10.400067,2.732277
3,ADCYAP1,6.255447,6.105541,6.515331,8.311376,6.834101,9.723572,4.007144,12.394558,9.501464,...,11.069999,8.276722,8.311376,4.561885,9.359651,8.800393,0.000000,5.748944,8.824586,0.000000
4,AES,9.825457,10.474256,9.918235,9.857322,9.542424,10.062736,9.333025,10.769199,10.602490,...,10.563344,9.748886,10.244780,10.000122,11.236185,10.034094,9.682293,9.240873,10.526041,10.261424

In [195]:
tmpDF.to_csv('164_bulk_data.txt', sep='\t',index=False)

In [196]:
finalBulkDataDF.shape

(421, 164)