In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import loadtxt
%matplotlib inline

In [2]:
#Experiment
#Read single Cell file
fullSingleDF = pd.read_csv('GSE75688_GEO_processed_Breast_Cancer_raw_TPM_matrix.txt', sep='\t')

In [3]:
fullSingleDF.head()

,gene_id,gene_name,gene_type,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
0,ENSG00000000003.10,TSPAN6,protein_coding,2.33,1.25,43.96,7.64,9.32,133.37,84.77,...,0.00,47.44,16.11,0.00,6.56,0.00,0.00,0.00,200.82,0.00
1,ENSG00000000005.5,TNMD,protein_coding,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,ENSG00000000419.8,DPM1,protein_coding,60.70,28.44,74.73,41.41,87.69,120.41,70.67,...,198.96,0.00,0.00,20.63,0.00,0.00,0.00,136.07,22.03,204.58
3,ENSG00000000457.9,SCYL3,protein_coding,47.93,4.43,9.89,7.61,7.32,12.42,12.02,...,0.00,10.96,0.00,0.00,0.00,0.27,0.00,0.07,0.19,9.52
4,ENSG00000000460.12,C1orf112,protein_coding,4.79,1.67,10.87,0.92,15.13,17.10,5.69,...,0.00,6.97,9.02,0.00,0.00,0.14,247.69,22.60,11.35,0.00

In [4]:
#new_header_3 = fullSingleDF.iloc[0] #grab the first row for the header
#fullSingleDF = fullSingleDF[1:] #take the data less the header row
#fullSingleDF.columns = new_header_3 #set the header row as the df header

In [5]:
geneNameDF = fullSingleDF['gene_name']

In [6]:
geneNameDF.head()

0      TSPAN6
1        TNMD
2        DPM1
3       SCYL3
4    C1orf112
Name: gene_name, dtype: object

In [9]:
markerGenesDF = pd.read_csv('markergenes.csv', sep=',')

In [10]:
markerGenesDF.head()

,HER2+,Bcells,Tcells,T helper cells,CD8 Tcells,Cytotoxic Cells,NK Cells,Dendritic Cells,Eosinophils,Macrophages,Mast Cells,Neutrophils
0,MUC19,MS4A1,PRKCQ,ICOS,CD8B,KLRD1,LOC643313,CD209,IL5RA,MARCO,PRG2,CSF3R
1,RPS12P26,TCL1A,CD3D,LRBA,CD8A,KLRF1,GAGE2,CCL17,KCNH2,CXCL5,CTSG,CYP4F3
2,CEACAM5,HLA-DOB,CD3G,ITM2A,PF4,GNLY,ZNF747,HSD11B1,TKTL1,SCG5,TPSAB1,VNN3
3,UBD,PNOC,CD28,FAM111A,PRR5,CTSW,XCL1,CCL13,EMR1,SULT1C2,SLC18A2,FPRL1
4,H19,KIAA0125,LCK,PHF10,SF1,KLRB1,XCL2,CCL22,CCR3,MSR1,MS4A2,KCNJ15

In [12]:
requiredGenesList = markerGenesDF.values.tolist()

In [23]:
#Make a python list of the marker genes - 1204 marker genes (also remove nans from the marker genes excel file)
requiredGenes = []
t = []
for i in range(len(requiredGenesList)):
    for j in range(len(requiredGenesList[i])):
        if requiredGenesList[i][j]!='nan':
            t.append(requiredGenesList[i][j])
req = []
for i in range(len(t)):
    if t[i]!='nan':
        req.append(t[i])
required = np.asarray(req)
requiredGenes = []
requiredGenes = [x for x in required if str(x) != 'nan']    
print ((requiredGenes))

['MUC19', 'MS4A1', 'PRKCQ', 'ICOS', 'CD8B', 'KLRD1', 'LOC643313', 'CD209', 'IL5RA', 'MARCO', 'PRG2', 'CSF3R', 'RPS12P26', 'TCL1A', 'CD3D', 'LRBA', 'CD8A', 'KLRF1', 'GAGE2', 'CCL17', 'KCNH2', 'CXCL5', 'CTSG', 'CYP4F3', 'CEACAM5', 'HLA-DOB', 'CD3G', 'ITM2A', 'PF4', 'GNLY', 'ZNF747', 'HSD11B1', 'TKTL1', 'SCG5', 'TPSAB1', 'VNN3', 'UBD', 'PNOC', 'CD28', 'FAM111A', 'PRR5', 'CTSW', 'XCL1', 'CCL13', 'EMR1', 'SULT1C2', 'SLC18A2', 'FPRL1', 'H19', 'KIAA0125', 'LCK', 'PHF10', 'SF1', 'KLRB1', 'XCL2', 'CCL22', 'CCR3', 'MSR1', 'MS4A2', 'KCNJ15', 'NDST4', 'CD19', 'TRAT1', 'NUP107', 'LIME1', 'KLRK1', 'AF107846', 'PPFIBP2', 'ACACB', 'CTSK', 'CPA3', 'MME', 'KRT20', 'CR2', 'BCL11B', 'SEC24C', 'DNAJB1', 'NKG7', 'SLC30A5', 'NPR1', 'THBS1', 'PTGDS', 'TPSB2', 'IL8RA', 'RP11-483P21.2', 'IGHG1', 'CD2', 'NAP1L4', 'ARHGAP8', 'GZMH', 'SGMS1', 'CD1B', 'GALC', 'COLEC12', 'TPSB2', 'IL8RB', 'BPIFB2', 'FCRL2', 'TRBC1', 'BATF', 'GZMM', 'SIGIRR', 'MCM3AP', 'VASH1', 'RNU2', 'GPC4', 'GATA2', 'FCGR3B', 'EREG', 'BLK', 'TRAC', 'ASF1A', 'SLC16A7', 'ZBTB16', 'TBXA2R', 'F13A1', 'CLC', 'PCOLCE2', 'HDC', 'DYSF', 'RP11-697E2.7', 'COCH', 'ITM2A', 'FRYL', 'SFRS7', 'RUNX3', 'CDC5L', 'CD1E', 'HIST1H1C', 'CHIT1', 'LOH11CR2A', 'FCAR', 'IL8', 'OSBPL10', 'SH2D1A', 'FUSIP1', 'APBA2', 'APOL3', 'LOC730096', 'MMP12', 'CYSLTR2', 'KAL1', 'SIGLEC6', 'CEACAM3', 'ZNF710', 'IGHA1', 'CD6', 'YME1L1', 'C4orf15', 'RORA', 'FUT5', 'FABP4', 'HRH4', 'CLEC5A', 'ELA2', 'HIST1H2BC', 'MTND2P28', 'TNFRSF17', 'CD96', 'TRA', 'LEPROTL1', 'APBA2', 'FGF18', 'CLEC10A', 'RNASE2', 'ME1', 'CMA1', 'HPSE', 'RP11-617F23.1', 'ABCB4', 'NCALD', 'RPA1', 'ZFP36L2', 'WHDC1L1', 'MRC2', 'SYT17', 'CAT', 'DNASE2B', 'PGDS', 'CPPED1', 'TFPI', 'BLNK', 'GIMAP5', 'UBE2L3', 'GADD45A', 'DUSP2', 'RP5-886K2.1', 'MS4A6A', 'LRP5L', 'CCL7', 'MLPH', 'CREB5', 'KRT86', 'GLDC', 'TRA', 'ANP32B', 'MYST3', 'GZMA', 'SPN', 'CTNS', 'SYNJ1', 'FN1', 'ADCYAP1', 'S100A12', 'NR1D1', 'MEF2C', 'CD3E', 'DDX50', 'ZEB1', 'PSMD4', 'GUCA1A', 'THBS4', 'CD163', 'SLC24A3', 'TNFRSF10C', 'NGRN', 'IGHM', 'SKAP1', 'C13orf34', 'ZNF609', 'PRX', 'CARD9', 'GPR44', 'GM2A', 'CALB2', 'SLC22A4', 'CXCL1', 'FAM30A', 'PPP2R5C', 'C12orf47', 'FZR1', 'ABCG2', 'KBTBD11', 'SCARB2', 'KIT', 'TECPR2', 'GRB7', 'SPIB', 'SLC25A12', 'THUMPD1', 'ZNF205', 'CD1A', 'HES1', 'BCAT1', 'TAL1', 'SLC25A37', 'IGF2BP2', 'BCL11A', 'ATF2', 'VAMP2', 'AL080130', 'PPARG', 'ABHD2', 'RAI14', 'ABCC4', 'BST1', 'SEMA4B', 'GNG7', 'CD28', 'ZNF91', 'ZNF528', 'RAP1GAP', 'TIPARP', 'COL8A2', 'PPM1H', 'CRISPLD2', 'CIB1', 'IGKC', 'GOLGA8A', 'ZNF22', 'MAPRE3', 'SLC7A8', 'SMPD3', 'APOE', 'MAOB', 'G0S2', 'MIEN1', 'CD72', 'IFNG', 'TMC6', 'BCL2', 'GSTT1', 'MYO15B', 'CHI3L1', 'HPGD', 'SIGLEC5', 'CDC6', 'MICAL3', 'LTA', 'FLT3LG', 'NM_017616', 'PDXK', 'TGIF1', 'ATG7', 'SCG2', 'CD93', 'SIX4', 'BACH2', 'APBB2', 'CDKN2AIP', 'ARL6IP2', 'FZD2', 'RRP12', 'CD84', 'PTGS1', 'MGAM', 'PTPN13', 'IGL', 'DOK5', 'TSC22D3', 'PDLIM4', 'CSF1R', 'IGSF2', 'FDX1', 'CEACAM8', 'ALPL', 'MSL1', 'CCR9', 'IL12RB2', 'TBCC', 'TRPV6', 'HS3ST2', 'RCOR3', 'MS4A4A', 'MPO', 'FPR1', 'CEACAM6', 'QRSL1', 'APOD', 'RBM3', 'LDB3', 'CH25H', 'EPN2', 'SGMS1', 'NR0B1', 'PDE4B', 'CAPS', 'DTNB', 'ZBTB32', 'ABT1', 'ADARB1', 'LMAN2L', 'C9orf156', 'EMP1', 'LOC339524', 'LILRB2', 'PPP1R1B', 'HLA-DQA1', 'CD38', 'C19orf6', 'SMEK1', 'SLC26A6', 'SIAH1', 'CYBB', 'AREG', 'SCN3A', 'CSF2', 'CAMLG', 'TCTN2', 'BLVRB', 'CD68', 'ERBB2', 'SLC15A2', 'CTLA4', 'PPP1R2', 'TINAGL1', 'NUDT9', 'PEG10', 'CD70', 'AES', 'IGFBP5', 'PREP', 'MED1', 'DPP4', 'KLF9', 'ALDH1B1', 'TM7SF4', 'AP3S2', 'EGFL6', 'PRF1', 'NCR1', 'TACSTD2', 'IDH2', 'BST2', 'KIR3DL2', 'CD1C', 'RP11-889L3.1', 'DUSP5', 'SPON2', 'CCL1', 'RPL19', 'LRP8', 'KIR2DL3', 'EBI3', 'CDK12', 'IL22', 'GZMB', 'INDO', 'RP11-690G19.3', 'DGKI', 'KIR3DS1', 'LAMP3', 'NLK', 'CCL4', 'KIR3DL1', 'OAS3', 'CASC3', 'GGT1', 'TCC38', 'IL3RA', 'STARD3', 'LRRN3', 'PMEPA1', 'MED31', 'SYNGR3', 'IL21R', 'TXNDC17', 'ATP9A', 'KIR3DL3', 'KPNA2', 'BTG3', 'KIR2DS5', 'CMAH', 'KIR2DS2', 'HBEGF', 'GTF3C1', 'SGCB', 'KIR2DS1', 'PMCH', 'S1PR5', 'AHI1', 'DUSP4', 'PTGIS', 'RRAD', 'CXCR6', 'PLA2G6', 'EVI5', 'NIBP', 'IL26', 'FOXJ1', 'MB', 'NEIL3', 'MADD', 'GSTA4', 'LPCAT4', 'PHEX', 'MPPED1', 'SMAD2', 'MUC3B', 'CENPF', 'ANK1', 'ADCY1', 'LOC728210', 'LAIR2', 'SNRPD1', 'MICAL2', 'DHFR', 'WDHD1', 'BIRC5', 'SLC39A14', 'HELLS', 'LIMA1', 'CDC25C', 'CDC7', 'GATA3']

In [18]:
t = pd.read_csv('mart_export.txt', sep=',')

In [19]:
geneNameDF = t.iloc[:,:]

In [20]:
geneNameDF.head()

,Gene stable ID,Gene name,Gene type,Gene start (bp),Gene end (bp),Chromosome/scaffold name
0,ENSG00000283891,MIR628,miRNA,55372940,55373034,15
1,ENSG00000251931,RNU6-871P,snRNA,59450673,59450772,12
2,ENSG00000207766,MIR626,miRNA,41691585,41691678,15
3,ENSG00000275323,AC012314.7,protein_coding,54201473,54208260,CHR_HSCHR19LRC_LRC_J_CTG3_1
4,ENSG00000276678,GHRLOS,misc_RNA,10287413,10287482,3

In [21]:
geneNameDF.to_csv('geneNames.csv', sep=',',index=False)

In [22]:
#Create a python dic of geneNames and geneIDs
import csv
reader = csv.reader(open('geneNames.csv', 'r'))
IDtoName = {}
NametoID = {}
for row in reader:
    k, v = row[0], row[1]
    IDtoName[k] = v
    NametoID[v] = k

In [24]:
#Get the geneIDs of the marker genes
requiredGenesIDs = []
for i in range(len(requiredGenes)):
    if requiredGenes[i] in NametoID.keys():
        requiredGenesIDs.append(str(NametoID[requiredGenes[i]]))
    else:
        print(requiredGenes[i])

LOC643313
GAGE2
EMR1
FPRL1
KIAA0125
AF107846
IL8RA
RP11-483P21.2
IL8RB
RNU2
RP11-697E2.7
SFRS7
LOH11CR2A
IL8
FUSIP1
LOC730096
KAL1
C4orf15
ELA2
TRA
RP11-617F23.1
WHDC1L1
PGDS
RP5-886K2.1
TRA
MYST3
C13orf34
GPR44
C12orf47
AL080130
NM_017616
ARL6IP2
IGL
IGSF2
C9orf156
LOC339524
C19orf6
SMEK1
TM7SF4
RP11-889L3.1
INDO
RP11-690G19.3
TCC38
CMAH
NIBP
MUC3B
LOC728210

In [25]:
print (len(requiredGenesIDs))

418

In [32]:
print(len(requiredGenes))

465

In [27]:
#Filter out only those rows from both the singleCellDF and bulkCellDF that belong to a marker gene
fullSingleDF = fullSingleDF[fullSingleDF['gene_name'].isin(requiredGenes)]

In [28]:
fullSingleDF.head()

,gene_id,gene_name,gene_type,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
40,ENSG00000003436.10,TFPI,protein_coding,0.04,17.61,0.27,88.27,32.64,79.54,26.71,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.15,4.77,0.0
50,ENSG00000004468.8,CD38,protein_coding,0.00,19.33,0.78,16.31,111.30,0.63,0.00,...,0.0,0.0,6.1,0.0,0.0,0.0,0.0,0.24,0.00,0.0
94,ENSG00000005381.6,MPO,protein_coding,0.00,0.00,0.99,10.92,6.88,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
99,ENSG00000005471.11,ABCB4,protein_coding,0.79,5.71,0.44,0.00,5.14,7.84,0.06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
151,ENSG00000006638.7,TBXA2R,protein_coding,0.00,2.36,0.44,0.00,0.35,0.00,0.19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0

In [29]:
fullSingleDF.drop(fullSingleDF.columns[[0,2]],axis=1,inplace=True)

In [31]:
fullSingleDF.shape

(422, 564)

In [33]:
fullSingleDF.head()

,gene_name,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,BC06_Pooled,BC07_Tumor,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
40,TFPI,0.04,17.61,0.27,88.27,32.64,79.54,26.71,11.88,29.65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.15,4.77,0.0
50,CD38,0.00,19.33,0.78,16.31,111.30,0.63,0.00,9.51,9.70,...,0.0,0.0,6.1,0.0,0.0,0.0,0.0,0.24,0.00,0.0
94,MPO,0.00,0.00,0.99,10.92,6.88,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
99,ABCB4,0.79,5.71,0.44,0.00,5.14,7.84,0.06,0.28,2.37,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
151,TBXA2R,0.00,2.36,0.44,0.00,0.35,0.00,0.19,0.80,1.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0

In [34]:
fullSingleDF.to_csv('temp_single_cell.txt', sep='\t',index=False)