In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import loadtxt
%matplotlib inline

In [4]:
#Read single Cell file
#singleCellDF = pd.read_csv('final_single_cell_data.txt', sep='\t',header=None)
singleCellDF = pd.read_csv('temp_single_cell.txt', sep='\t')

In [5]:
#Remove everything from . till end of string
singleCellDF.head()

,gene_name,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,BC06_Pooled,BC07_Tumor,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
0,TFPI,0.04,17.61,0.27,88.27,32.64,79.54,26.71,11.88,29.65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.15,4.77,0.0
1,CD38,0.00,19.33,0.78,16.31,111.30,0.63,0.00,9.51,9.70,...,0.0,0.0,6.1,0.0,0.0,0.0,0.0,0.24,0.00,0.0
2,MPO,0.00,0.00,0.99,10.92,6.88,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
3,ABCB4,0.79,5.71,0.44,0.00,5.14,7.84,0.06,0.28,2.37,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
4,TBXA2R,0.00,2.36,0.44,0.00,0.35,0.00,0.19,0.80,1.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0

In [6]:
#Make first row the column names for both singleCellDF and bulkCellDF
#new_header = singleCellDF.iloc[0] #grab the first row for the header
#singleCellDF = singleCellDF[1:] #take the data less the header row
#singleCellDF.columns = new_header #set the header row as the df header

In [8]:
#Calculate the average and take log2(TPM+1)
singleCellDF['BC_01'] = np.log2(singleCellDF.iloc[:,15:41].astype(float).mean(axis=1).add(1))
singleCellDF['BC_02'] = np.log2(singleCellDF.iloc[:,41:97].astype(float).mean(axis=1).add(1))
singleCellDF['BC_03'] = np.log2(singleCellDF.iloc[:,97:134].astype(float).mean(axis=1).add(1))
singleCellDF['BC_03LN'] = np.log2(singleCellDF.iloc[:,134:189].astype(float).mean(axis=1).add(1))
singleCellDF['BC_04'] = np.log2(singleCellDF.iloc[:,189:248].astype(float).mean(axis=1).add(1))
singleCellDF['BC_05'] = np.log2(singleCellDF.iloc[:,248:325].astype(float).mean(axis=1).add(1))
singleCellDF['BC_06'] = np.log2(singleCellDF.iloc[:,325:350].astype(float).mean(axis=1).add(1))
singleCellDF['BC_07'] = np.log2(singleCellDF.iloc[:,350:401].astype(float).mean(axis=1).add(1))
singleCellDF['BC_07LN'] = np.log2(singleCellDF.iloc[:,401:454].astype(float).mean(axis=1).add(1))
singleCellDF['BC_08'] = np.log2(singleCellDF.iloc[:,454:477].astype(float).mean(axis=1).add(1))
singleCellDF['BC_09'] = np.log2(singleCellDF.iloc[:,477:537].astype(float).mean(axis=1).add(1))
singleCellDF['BC_10'] = np.log2(singleCellDF.iloc[:,537:553].astype(float).mean(axis=1).add(1))
singleCellDF['BC_11'] = np.log2(singleCellDF.iloc[:,553:564].astype(float).mean(axis=1).add(1))

In [9]:
singleCellDF.head()

,gene_name,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,BC06_Pooled,BC07_Tumor,...,BC_03LN,BC_04,BC_05,BC_06,BC_07,BC_07LN,BC_08,BC_09,BC_10,BC_11
0,TFPI,0.04,17.61,0.27,88.27,32.64,79.54,26.71,11.88,29.65,...,4.228413,5.598288,4.586780,1.526069,6.556976,2.644596,1.390046,2.084858,0.000000,1.819668
1,CD38,0.00,19.33,0.78,16.31,111.30,0.63,0.00,9.51,9.70,...,7.024132,0.389380,0.000000,4.325674,2.696954,4.994127,0.495695,6.107203,0.071248,0.775529
2,MPO,0.00,0.00,0.99,10.92,6.88,0.00,0.00,0.00,0.00,...,2.399445,0.011205,0.000000,0.016068,0.679132,0.003263,0.000000,0.000000,0.000000,0.000000
3,ABCB4,0.79,5.71,0.44,0.00,5.14,7.84,0.06,0.28,2.37,...,0.373661,0.575969,1.865790,3.221382,2.328701,2.421725,0.031027,2.583118,0.000000,0.000000
4,TBXA2R,0.00,2.36,0.44,0.00,0.35,0.00,0.19,0.80,1.75,...,0.161155,0.968231,0.085124,0.000000,0.688290,0.395580,0.264079,0.000000,0.083213,0.000000

In [10]:
#Do necessary preprocessing to get the final signatureMatrixDF
finalSingleCellDF = singleCellDF.iloc[:,564:]
finalSingleCellDF.insert(0, 'gene_name', singleCellDF.iloc[:,0])

In [12]:
finalSingleCellDF.head()

,gene_name,BC_01,BC_02,BC_03,BC_03LN,BC_04,BC_05,BC_06,BC_07,BC_07LN,BC_08,BC_09,BC_10,BC_11
0,TFPI,0.026391,0.000000,6.344181,4.228413,5.598288,4.586780,1.526069,6.556976,2.644596,1.390046,2.084858,0.000000,1.819668
1,CD38,0.009402,0.051621,5.028975,7.024132,0.389380,0.000000,4.325674,2.696954,4.994127,0.495695,6.107203,0.071248,0.775529
2,MPO,0.000000,0.000000,2.229172,2.399445,0.011205,0.000000,0.016068,0.679132,0.003263,0.000000,0.000000,0.000000,0.000000
3,ABCB4,0.000000,0.523203,4.727185,0.373661,0.575969,1.865790,3.221382,2.328701,2.421725,0.031027,2.583118,0.000000,0.000000
4,TBXA2R,0.000000,0.167174,0.000000,0.161155,0.968231,0.085124,0.000000,0.688290,0.395580,0.264079,0.000000,0.083213,0.000000

In [13]:
finalSingleCellDF.shape

(422, 14)

In [14]:
#Save the finalSignature Matrix and run CIBERSORT on it
finalSingleCellDF.to_csv('singleCellMatrix.txt', sep='\t',index=False)