In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import loadtxt
%matplotlib inline

In [2]:
#Experiment
#Read single Cell file
fullSingleDF = pd.read_csv('GSE75688_GEO_processed_Breast_Cancer_raw_TPM_matrix.txt', sep='\t',header=None)

/Users/rahulbhansali1/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
fullSingleDF.head()

,0,1,2,3,4,5,6,7,8,9,...,556,557,558,559,560,561,562,563,564,565
0,gene_id,gene_name,gene_type,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
1,ENSG00000000003.10,TSPAN6,protein_coding,2.33,1.25,43.96,7.64,9.32,133.37,84.77,...,0,47.44,16.11,0,6.56,0,0,0,200.82,0
2,ENSG00000000005.5,TNMD,protein_coding,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000000419.8,DPM1,protein_coding,60.7,28.44,74.73,41.41,87.69,120.41,70.67,...,198.96,0,0,20.63,0,0,0,136.07,22.03,204.58
4,ENSG00000000457.9,SCYL3,protein_coding,47.93,4.43,9.89,7.61,7.32,12.42,12.02,...,0,10.96,0,0,0,0.27,0,0.07,0.19,9.52

In [4]:
new_header_3 = fullSingleDF.iloc[0] #grab the first row for the header
fullSingleDF = fullSingleDF[1:] #take the data less the header row
fullSingleDF.columns = new_header_3 #set the header row as the df header

In [5]:
fullSingleDF.head()

,gene_id,gene_name,gene_type,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
1,ENSG00000000003.10,TSPAN6,protein_coding,2.33,1.25,43.96,7.64,9.32,133.37,84.77,...,0,47.44,16.11,0,6.56,0,0,0,200.82,0
2,ENSG00000000005.5,TNMD,protein_coding,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000000419.8,DPM1,protein_coding,60.7,28.44,74.73,41.41,87.69,120.41,70.67,...,198.96,0,0,20.63,0,0,0,136.07,22.03,204.58
4,ENSG00000000457.9,SCYL3,protein_coding,47.93,4.43,9.89,7.61,7.32,12.42,12.02,...,0,10.96,0,0,0,0.27,0,0.07,0.19,9.52
5,ENSG00000000460.12,C1orf112,protein_coding,4.79,1.67,10.87,0.92,15.13,17.1,5.69,...,0,6.97,9.02,0,0,0.14,247.69,22.6,11.35,0

In [6]:
geneNameDF = fullSingleDF['gene_name']

In [7]:
geneNameDF.head()

1      TSPAN6
2        TNMD
3        DPM1
4       SCYL3
5    C1orf112
Name: gene_name, dtype: object

In [8]:
markerGenesDF = pd.read_csv('markergenes.csv', sep=',',header=None)

In [9]:
markerGenesDF.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,ER+,HER2+,TNBC,Bcells,Tcells,T helper cells,CD8 Tcells,Cytotoxic Cells,NK Cells,Dendritic Cells,Eosinophils,Macrophages,Mast Cells,Neutrophils
1,CPB1,MUC19,FABP7,MS4A1,PRKCQ,ICOS,CD8B,KLRD1,LOC643313,CD209,IL5RA,MARCO,PRG2,CSF3R
2,RP11-53O19.1,RPS12P26,TSPAN8,TCL1A,CD3D,LRBA,CD8A,KLRF1,GAGE2,CCL17,KCNH2,CXCL5,CTSG,CYP4F3
3,TFF1,CEACAM5,CYP4Z1,HLA-DOB,CD3G,ITM2A,PF4,GNLY,ZNF747,HSD11B1,TKTL1,SCG5,TPSAB1,VNN3
4,PVALB,UBD,HOXA10,PNOC,CD28,FAM111A,PRR5,CTSW,XCL1,CCL13,EMR1,SULT1C2,SLC18A2,FPRL1

In [10]:
markerGenesDF = markerGenesDF[1:]

In [11]:
markerGenesDF.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
1,CPB1,MUC19,FABP7,MS4A1,PRKCQ,ICOS,CD8B,KLRD1,LOC643313,CD209,IL5RA,MARCO,PRG2,CSF3R
2,RP11-53O19.1,RPS12P26,TSPAN8,TCL1A,CD3D,LRBA,CD8A,KLRF1,GAGE2,CCL17,KCNH2,CXCL5,CTSG,CYP4F3
3,TFF1,CEACAM5,CYP4Z1,HLA-DOB,CD3G,ITM2A,PF4,GNLY,ZNF747,HSD11B1,TKTL1,SCG5,TPSAB1,VNN3
4,PVALB,UBD,HOXA10,PNOC,CD28,FAM111A,PRR5,CTSW,XCL1,CCL13,EMR1,SULT1C2,SLC18A2,FPRL1
5,ANKRD30B,H19,CLDN1,KIAA0125,LCK,PHF10,SF1,KLRB1,XCL2,CCL22,CCR3,MSR1,MS4A2,KCNJ15

In [12]:
requiredGenesList = markerGenesDF.values.tolist()

In [13]:
#Make a python list of the marker genes - 1204 marker genes (also remove nans from the marker genes excel file)
requiredGenes = []
t = []
for i in range(len(requiredGenesList)):
    for j in range(len(requiredGenesList[i])):
        if requiredGenesList[i][j]!='nan':
            t.append(requiredGenesList[i][j])
req = []
for i in range(len(t)):
    if t[i]!='nan':
        req.append(t[i])
required = np.asarray(req)
requiredGenes = []
requiredGenes = [x for x in required if str(x) != 'nan']    
print (len(requiredGenes))

602

In [15]:
t = pd.read_csv('mart_export.txt', sep=',',header=None)

In [16]:
geneNameDF = t.iloc[1:,:]

In [17]:
geneNameDF.head()

,0,1,2,3,4,5
1,ENSG00000283891,MIR628,miRNA,55372940,55373034,15
2,ENSG00000251931,RNU6-871P,snRNA,59450673,59450772,12
3,ENSG00000207766,MIR626,miRNA,41691585,41691678,15
4,ENSG00000275323,AC012314.7,protein_coding,54201473,54208260,CHR_HSCHR19LRC_LRC_J_CTG3_1
5,ENSG00000276678,GHRLOS,misc_RNA,10287413,10287482,3

In [18]:
geneNameDF.to_csv('geneNames.csv', sep=',',index=False)

In [19]:
#Create a python dic of geneNames and geneIDs
import csv
reader = csv.reader(open('geneNames.csv', 'r'))
IDtoName = {}
NametoID = {}
for row in reader:
    k, v = row[0], row[1]
    IDtoName[k] = v
    NametoID[v] = k

In [20]:
#Get the geneIDs of the marker genes
requiredGenesIDs = []
for i in range(len(requiredGenes)):
    if requiredGenes[i] in NametoID.keys():
        requiredGenesIDs.append(str(NametoID[requiredGenes[i]]))
    else:
        print(requiredGenes[i])

LOC643313
RP11-53O19.1
GAGE2
EMR1
FPRL1
KIAA0125
AF107846
IL8RA
RP11-483P21.2
IL8RB
RNU2
RP11-697E2.7
SFRS7
LOH11CR2A
IL8
RP11-48O20.4
FUSIP1
LOC730096
KAL1
C4orf15
ELA2
RP11-64B16.2
TRA
RP11-617F23.1
WHDC1L1
PGDS
RP5-886K2.1
TRA
MYST3
C13orf34
GPR44
C12orf47
AC026806.2
AL080130
NM_017616
ARL6IP2
IGL
IGSF2
C9orf156
LOC339524
C19orf6
SMEK1
EFCAB4A
TM7SF4
KIAA1467
RP11-889L3.1
INDO
RP11-690G19.3
TCC38
RP1-257A7.5
RP11-96D1.10
RP11-353N4.6
CMAH
CTD-2314B22.3
PPAPDC1B
NIBP
RP11-658F2.8
ADCK3
MUC3B
RP11-110G21.2
RP11-640M9.1
RP13-39P12.3
LOC728210

In [21]:
print (len(requiredGenesIDs))

539

In [22]:
print(requiredGenes)

['CPB1', 'MUC19', 'FABP7', 'MS4A1', 'PRKCQ', 'ICOS', 'CD8B', 'KLRD1', 'LOC643313', 'CD209', 'IL5RA', 'MARCO', 'PRG2', 'CSF3R', 'RP11-53O19.1', 'RPS12P26', 'TSPAN8', 'TCL1A', 'CD3D', 'LRBA', 'CD8A', 'KLRF1', 'GAGE2', 'CCL17', 'KCNH2', 'CXCL5', 'CTSG', 'CYP4F3', 'TFF1', 'CEACAM5', 'CYP4Z1', 'HLA-DOB', 'CD3G', 'ITM2A', 'PF4', 'GNLY', 'ZNF747', 'HSD11B1', 'TKTL1', 'SCG5', 'TPSAB1', 'VNN3', 'PVALB', 'UBD', 'HOXA10', 'PNOC', 'CD28', 'FAM111A', 'PRR5', 'CTSW', 'XCL1', 'CCL13', 'EMR1', 'SULT1C2', 'SLC18A2', 'FPRL1', 'ANKRD30B', 'H19', 'CLDN1', 'KIAA0125', 'LCK', 'PHF10', 'SF1', 'KLRB1', 'XCL2', 'CCL22', 'CCR3', 'MSR1', 'MS4A2', 'KCNJ15', 'LINC00173', 'NDST4', 'TMSB15A', 'CD19', 'TRAT1', 'NUP107', 'LIME1', 'KLRK1', 'AF107846', 'PPFIBP2', 'ACACB', 'CTSK', 'CPA3', 'MME', 'DSCAM-AS1', 'KRT20', 'C10orf10', 'CR2', 'BCL11B', 'SEC24C', 'DNAJB1', 'NKG7', 'SLC30A5', 'NPR1', 'THBS1', 'PTGDS', 'TPSB2', 'IL8RA', 'IGHG1', 'RP11-483P21.2', 'TRPV6', 'IGHG1', 'CD2', 'NAP1L4', 'ARHGAP8', 'GZMH', 'SGMS1', 'CD1B', 'GALC', 'COLEC12', 'TPSB2', 'IL8RB', 'SERPINA5', 'BPIFB2', 'HOXA9', 'FCRL2', 'TRBC1', 'BATF', 'GZMM', 'SIGIRR', 'MCM3AP', 'VASH1', 'RNU2', 'GPC4', 'GATA2', 'FCGR3B', 'ESR1', 'EREG', 'ATP13A4', 'BLK', 'TRAC', 'ASF1A', 'SLC16A7', 'ZBTB16', 'TBXA2R', 'F13A1', 'CLC', 'PCOLCE2', 'HDC', 'DYSF', 'LRP2', 'RP11-697E2.7', 'GLYATL2', 'COCH', 'ITM2A', 'FRYL', 'SFRS7', 'RUNX3', 'CDC5L', 'CD1E', 'HIST1H1C', 'CHIT1', 'LOH11CR2A', 'FCAR', 'IGLC3', 'IL8', 'RP11-48O20.4', 'OSBPL10', 'SH2D1A', 'FUSIP1', 'APBA2', 'APOL3', 'LOC730096', 'MMP12', 'CYSLTR2', 'KAL1', 'SIGLEC6', 'CEACAM3', 'CA12', 'ZNF710', 'DYRK3', 'IGHA1', 'CD6', 'YME1L1', 'C4orf15', 'RORA', 'FUT5', 'FABP4', 'HRH4', 'CLEC5A', 'ELA2', 'HIST1H2BC', 'RP11-64B16.2', 'MTND2P28', 'MUCL1', 'TNFRSF17', 'CD96', 'TRA', 'LEPROTL1', 'APBA2', 'FGF18', 'CLEC10A', 'RNASE2', 'ME1', 'CMA1', 'HPSE', 'SLC7A2', 'RP11-617F23.1', 'ID4', 'ABCB4', 'NCALD', 'RPA1', 'ZFP36L2', 'WHDC1L1', 'MRC2', 'SYT17', 'CAT', 'DNASE2B', 'PGDS', 'CPPED1', 'AFF3', 'TFPI', 'FGFR2', 'BLNK', 'GIMAP5', 'UBE2L3', 'GADD45A', 'DUSP2', 'RP5-886K2.1', 'MS4A6A', 'LRP5L', 'CCL7', 'MLPH', 'CREB5', 'IGFBP4', 'KRT86', 'SHOX2', 'GLDC', 'TRA', 'ANP32B', 'MYST3', 'GZMA', 'SPN', 'CTNS', 'SYNJ1', 'FN1', 'ADCYAP1', 'S100A12', 'GSTM3', 'NR1D1', 'Z83851.1', 'MEF2C', 'CD3E', 'DDX50', 'ZEB1', 'PSMD4', 'GUCA1A', 'THBS4', 'CD163', 'SLC24A3', 'TNFRSF10C', 'ANKRD30A', 'NGRN', 'CD82', 'IGHM', 'SKAP1', 'C13orf34', 'ZNF609', 'PRX', 'CARD9', 'GPR44', 'GM2A', 'CALB2', 'SLC22A4', 'GSTT1', 'CXCL1', 'COL6A1', 'FAM30A', 'PPP2R5C', 'C12orf47', 'FZR1', 'ABCG2', 'KBTBD11', 'SCARB2', 'KIT', 'TECPR2', 'GSTM1', 'GRB7', 'KRT23', 'SPIB', 'SLC25A12', 'THUMPD1', 'ZNF205', 'CD1A', 'HES1', 'BCAT1', 'TAL1', 'SLC25A37', 'AC026806.2', 'IGF2BP2', 'GCHFR', 'BCL11A', 'ATF2', 'VAMP2', 'AL080130', 'PPARG', 'ABHD2', 'RAI14', 'ABCC4', 'BST1', 'C19orf33', 'SEMA4B', 'PRICKLE1', 'GNG7', 'CD28', 'ZNF91', 'ZNF528', 'RAP1GAP', 'TIPARP', 'COL8A2', 'PPM1H', 'CRISPLD2', 'STC2', 'CIB1', 'GCNT2', 'IGKC', 'GOLGA8A', 'ZNF22', 'MAPRE3', 'SLC7A8', 'SMPD3', 'APOE', 'MAOB', 'G0S2', 'HSPB8', 'MIEN1', 'KHDRBS3', 'CD72', 'IFNG', 'TMC6', 'BCL2', 'GSTT1', 'MYO15B', 'CHI3L1', 'HPGD', 'SIGLEC5', 'RPL29P11', 'CDC6', 'SIPA1L2', 'MICAL3', 'LTA', 'FLT3LG', 'NM_017616', 'PDXK', 'TGIF1', 'ATG7', 'SCG2', 'CD93', 'FBP1', 'SIX4', 'LMO4', 'BACH2', 'APBB2', 'CDKN2AIP', 'ARL6IP2', 'FZD2', 'RRP12', 'CD84', 'PTGS1', 'MGAM', 'AGR3', 'PTPN13', 'TFAP2B', 'IGL', 'DOK5', 'TSC22D3', 'PDLIM4', 'CSF1R', 'IGSF2', 'FDX1', 'CEACAM8', 'ALPL', 'TCEAL1', 'MSL1', 'SLC43A3', 'CCR9', 'IL12RB2', 'TBCC', 'TRPV6', 'HS3ST2', 'RCOR3', 'MS4A4A', 'MPO', 'FPR1', 'CYP4B1', 'CEACAM6', 'FURIN', 'QRSL1', 'APOD', 'RBM3', 'LDB3', 'CH25H', 'EPN2', 'SGMS1', 'NR0B1', 'PDE4B', 'SYT1', 'CAPS', 'ELF5', 'DTNB', 'ZBTB32', 'ABT1', 'ADARB1', 'LMAN2L', 'C9orf156', 'EMP1', 'LOC339524', 'LILRB2', 'COX6C', 'PPP1R1B', 'C1orf116', 'HLA-DQA1', 'CD38', 'C19orf6', 'SMEK1', 'SLC26A6', 'SIAH1', 'CYBB', 'MT1E', 'AREG', 'ADD3', 'SCN3A', 'CSF2', 'CAMLG', 'TCTN2', 'BLVRB', 'CD68', 'SYTL2', 'ERBB2', 'EFNA3', 'SLC15A2', 'CTLA4', 'PPP1R2', 'TINAGL1', 'NUDT9', 'THSD4', 'PEG10', 'EFCAB4A', 'CD70', 'AES', 'IGFBP5', 'PREP', 'IFI6', 'MED1', 'LTF', 'DPP4', 'KLF9', 'ALDH1B1', 'TM7SF4', 'KIAA1467', 'AP3S2', 'LRRC31', 'EGFL6', 'PRF1', 'NCR1', 'TACSTD2', 'SLC39A6', 'IDH2', 'ARL4C', 'BST2', 'KIR3DL2', 'CD1C', 'ABCD3', 'RP11-889L3.1', 'GPNMB', 'DUSP5', 'SPON2', 'CCL1', 'SERPINA3', 'RPL19', 'VIM', 'LRP8', 'KIR2DL3', 'EBI3', 'DEGS2', 'CDK12', 'SDR16C5', 'IL22', 'GZMB', 'INDO', 'ERLIN2', 'RP11-690G19.3', 'RHOV', 'DGKI', 'KIR3DS1', 'LAMP3', 'HEBP1', 'NLK', 'PXDC1', 'CCL4', 'KIR3DL1', 'OAS3', 'BCL2', 'CASC3', 'MALL', 'GGT1', 'TCC38', 'IL3RA', 'TCEAL3', 'STARD3', 'YAP1', 'LRRN3', 'PMEPA1', 'PPT1', 'MED31', 'A2ML1', 'SYNGR3', 'IL21R', 'SLC7A8', 'TXNDC17', 'RP1-257A7.5', 'ATP9A', 'KIR3DL3', 'RP11-96D1.10', 'KPNA2', 'RP11-353N4.6', 'BTG3', 'KIR2DS5', 'HIST1H4H', 'ZBTB18', 'CMAH', 'KIR2DS2', 'PI15', 'CTD-2314B22.3', 'HBEGF', 'GTF3C1', 'PPAPDC1B', 'GALNT3', 'SGCB', 'KIR2DS1', 'RARRES3', 'BCL11A', 'PMCH', 'S1PR5', 'GALNT6', 'CXADR', 'AHI1', 'DUSP4', 'IL6ST', 'SSFA2', 'PTGIS', 'RRAD', 'MYC', 'ADM', 'CXCR6', 'PLA2G6', 'BST2', 'GUCY1A3', 'EVI5', 'NIBP', 'RP11-658F2.8', 'GSTP1', 'IL26', 'FOXJ1', 'MRPS30', 'ADCK3', 'MB', 'MAPT', 'SLC25A37', 'NEIL3', 'MADD', 'AMFR', 'SFRP1', 'GSTA4', 'LPCAT4', 'TCEAL4', 'PRNP', 'PHEX', 'MPPED1', 'MED13L', 'DEGS1', 'SMAD2', 'MUC3B', 'ISG15', 'RP11-110G21.2', 'CENPF', 'NDUFC2', 'RBMS1', 'ANK1', 'TIMP3', 'RP11-640M9.1', 'ADCY1', 'RP13-39P12.3', 'AL589743.1', 'LOC728210', 'PARD6B', 'ATF3', 'LAIR2', 'SIVA1', 'SNRPD1', 'TACSTD2', 'MICAL2', 'HEBP2', 'DHFR', 'WDHD1', 'BIRC5', 'SLC39A14', 'HELLS', 'LIMA1', 'CDC25C', 'CDC7', 'GATA3']

In [23]:
#Filter out only those rows from both the singleCellDF and bulkCellDF that belong to a marker gene
fullSingleDF = fullSingleDF[fullSingleDF['gene_name'].isin(requiredGenes)]

In [25]:
fullSingleDF.drop(fullSingleDF.columns[[1,2]],axis=1,inplace=True)

In [26]:
fullSingleDF.shape

(551, 564)

In [27]:
fullSingleDF.head()

,gene_id,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,BC06_Pooled,BC07_Tumor,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
41,ENSG00000003436.10,0.04,17.61,0.27,88.27,32.64,79.54,26.71,11.88,29.65,...,0,0,0,0,0,0,0,21.15,4.77,0
45,ENSG00000003989.12,73.57,22.6,16.29,4.14,1.4,0.38,1.86,0,1.97,...,0,0,0,0,1.63,0,0,0.06,0,0
51,ENSG00000004468.8,0,19.33,0.78,16.31,111.3,0.63,0,9.51,9.7,...,0,0,6.1,0,0,0,0,0.24,0,0
95,ENSG00000005381.6,0,0,0.99,10.92,6.88,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,ENSG00000005471.11,0.79,5.71,0.44,0,5.14,7.84,0.06,0.28,2.37,...,0,0,0,0,0,0,0,0,0,0

In [28]:
fullSingleDF.to_csv('temp_single_cell.txt', sep='\t',index=False)