In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import loadtxt
%matplotlib inline

In [27]:
#Experiment
#Read single Cell file
fullSingleDF = pd.read_csv('GSE75688_GEO_processed_Breast_Cancer_raw_TPM_matrix.txt', sep='\t')

In [28]:
fullSingleDF.head()

,gene_id,gene_name,gene_type,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
0,ENSG00000000003.10,TSPAN6,protein_coding,2.33,1.25,43.96,7.64,9.32,133.37,84.77,...,0.00,47.44,16.11,0.00,6.56,0.00,0.00,0.00,200.82,0.00
1,ENSG00000000005.5,TNMD,protein_coding,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,ENSG00000000419.8,DPM1,protein_coding,60.70,28.44,74.73,41.41,87.69,120.41,70.67,...,198.96,0.00,0.00,20.63,0.00,0.00,0.00,136.07,22.03,204.58
3,ENSG00000000457.9,SCYL3,protein_coding,47.93,4.43,9.89,7.61,7.32,12.42,12.02,...,0.00,10.96,0.00,0.00,0.00,0.27,0.00,0.07,0.19,9.52
4,ENSG00000000460.12,C1orf112,protein_coding,4.79,1.67,10.87,0.92,15.13,17.10,5.69,...,0.00,6.97,9.02,0.00,0.00,0.14,247.69,22.60,11.35,0.00

In [29]:
#new_header_3 = fullSingleDF.iloc[0] #grab the first row for the header
#fullSingleDF = fullSingleDF[1:] #take the data less the header row
#fullSingleDF.columns = new_header_3 #set the header row as the df header

In [30]:
geneNameDF = fullSingleDF['gene_name']

In [31]:
markerGenesDF = pd.read_csv('markergenes_all.csv', sep=',')

In [32]:
markerGenesDF.head()

,HER2+,Bcells,Tcells,T helper cells,CD8 Tcells,Cytotoxic Cells,NK Cells,Dendritic Cells,Eosinophils,Macrophages,Mast Cells,Neutrophils,ER+,TNBC
0,MUC19,MS4A1,PRKCQ,ICOS,CD8B,KLRD1,LOC643313,CD209,IL5RA,MARCO,PRG2,CSF3R,CPB1,FABP7
1,RPS12P26,TCL1A,CD3D,LRBA,CD8A,KLRF1,GAGE2,CCL17,KCNH2,CXCL5,CTSG,CYP4F3,RP11-53O19.1,TSPAN8
2,CEACAM5,HLA-DOB,CD3G,ITM2A,PF4,GNLY,ZNF747,HSD11B1,TKTL1,SCG5,TPSAB1,VNN3,TFF1,CYP4Z1
3,UBD,PNOC,CD28,FAM111A,PRR5,CTSW,XCL1,CCL13,EMR1,SULT1C2,SLC18A2,FPRL1,PVALB,HOXA10
4,H19,KIAA0125,LCK,PHF10,SF1,KLRB1,XCL2,CCL22,CCR3,MSR1,MS4A2,KCNJ15,ANKRD30B,CLDN1

In [33]:
requiredGenesList = markerGenesDF.values.tolist()

In [34]:
#Make a python list of the marker genes - 1204 marker genes (also remove nans from the marker genes excel file)
requiredGenes = []
t = []
for i in range(len(requiredGenesList)):
    for j in range(len(requiredGenesList[i])):
        if requiredGenesList[i][j]!='nan':
            t.append(requiredGenesList[i][j])
req = []
for i in range(len(t)):
    if t[i]!='nan':
        req.append(t[i])
required = np.asarray(req)
requiredGenes = []
requiredGenes = [x for x in required if str(x) != 'nan']    
requiredGenes = list(set(requiredGenes))
print ((requiredGenes))

['GLDC', 'GSTM1', 'CAMLG', 'LAMP3', 'SLC25A37', 'CD93', 'TFF1', 'NPR1', 'C19orf33', 'RP11-658F2.8', 'TRPV6', 'GATA2', 'MADD', 'EVI5', 'MYC', 'DYSF', 'IGF2BP2', 'GNLY', 'TINAGL1', 'MRPS30', 'NKG7', 'SYTL2', 'PRNP', 'PPARG', 'GPNMB', 'PHEX', 'CD8B', 'A2ML1', 'GIMAP5', 'PRICKLE1', 'CYBB', 'INDO', 'XCL1', 'SLC39A6', 'TCEAL1', 'C1orf116', 'FOXJ1', 'ASF1A', 'SMPD3', 'CD3G', 'AL589743.1', 'SLC39A14', 'SLC22A4', 'ADD3', 'PRKCQ', 'FRYL', 'ME1', 'ID4', 'KIT', 'MS4A4A', 'GZMM', 'ARL6IP2', 'TSPAN8', 'BACH2', 'AFF3', 'FZR1', 'KIR2DS5', 'KAL1', 'G0S2', 'LAIR2', 'RPS12P26', 'RP11-697E2.7', 'HS3ST2', 'LOC643313', 'EMR1', 'IGL', 'TCTN2', 'COX6C', 'FGF18', 'SMAD2', 'LOH11CR2A', 'KIAA1467', 'SYT17', 'CDKN2AIP', 'TKTL1', 'CD3E', 'THBS1', 'GCHFR', 'SH2D1A', 'ABCC4', 'IFI6', 'TNFRSF17', 'LINC00173', 'SIVA1', 'KLRF1', 'MAPT', 'WHDC1L1', 'IDH2', 'CXCL5', 'CCL4', 'APOE', 'EPN2', 'PPFIBP2', 'GSTA4', 'C4orf15', 'HSD11B1', 'TRBC1', 'BLVRB', 'TGIF1', 'APBB2', 'TBXA2R', 'TRA', 'EGFL6', 'PPT1', 'TPSAB1', 'IL6ST', 'COLEC12', 'NDUFC2', 'ICOS', 'IGFBP4', 'SMEK1', 'KHDRBS3', 'SHOX2', 'ZNF710', 'GSTM3', 'WDHD1', 'XCL2', 'FUT5', 'PRF1', 'Z83851.1', 'HRH4', 'CD209', 'ATG7', 'GALNT6', 'MAOB', 'RP11-889L3.1', 'FN1', 'ADCY1', 'IL3RA', 'DDX50', 'KIR2DL3', 'CD68', 'CYSLTR2', 'CASC3', 'PCOLCE2', 'SDR16C5', 'TMSB15A', 'NDST4', 'TECPR2', 'FLT3LG', 'SPON2', 'BCL11B', 'RP11-640M9.1', 'CMAH', 'PDLIM4', 'APBA2', 'KRT86', 'GLYATL2', 'PMEPA1', 'IFNG', 'ADCYAP1', 'AF107846', 'SIGIRR', 'TM7SF4', 'CCL22', 'SPN', 'ZNF747', 'SLC30A5', 'THBS4', 'CREB5', 'EBI3', 'ABCB4', 'DNASE2B', 'PRR5', 'DNAJB1', 'HPGD', 'SYT1', 'NAP1L4', 'SCG2', 'FURIN', 'MUCL1', 'SIPA1L2', 'PNOC', 'RP11-353N4.6', 'CPPED1', 'CSF3R', 'AGR3', 'KLRK1', 'MIEN1', 'GPC4', 'KCNJ15', 'CLC', 'KIR3DL2', 'CXADR', 'LILRB2', 'DUSP5', 'PF4', 'PPP2R5C', 'TRAC', 'VASH1', 'SIX4', 'HES1', 'GCNT2', 'KIR3DL3', 'ERBB2', 'CEACAM8', 'SGCB', 'SEC24C', 'CCL7', 'DUSP4', 'DPP4', 'SIGLEC6', 'HDC', 'CD1A', 'DOK5', 'MALL', 'LRP2', 'BST2', 'SKAP1', 'ABCD3', 'KRT20', 'IL8RB', 'ATP13A4', 'ARHGAP8', 'CYP4Z1', 'RP5-886K2.1', 'TCEAL3', 'ELA2', 'STARD3', 'MAPRE3', 'KLRD1', 'KLRB1', 'TFPI', 'HBEGF', 'CTSW', 'CDC6', 'OAS3', 'ISG15', 'CEACAM5', 'CD38', 'SLC7A2', 'GZMA', 'LEPROTL1', 'BATF', 'CTLA4', 'RBMS1', 'COL6A1', 'RP11', 'CD1B', 'CH25H', 'CRISPLD2', 'NUDT9', 'LTF', 'GALC', 'LOC339524', 'CD96', 'CD84', 'ADCK3', 'H19', 'TFAP2B', 'PTGDS', 'FZD2', 'CYP4B1', 'RP13-39P12.3', 'ZNF609', 'CD3D', 'GZMH', 'DEGS1', 'GADD45A', 'COL8A2', 'FPRL1', 'MS4A2', 'VNN3', 'PRG2', 'RCOR3', 'GSTP1', 'PTGS1', 'GOLGA8A', 'AP3S2', 'YME1L1', 'C13orf34', 'HIST1H2BC', 'KIR2DS2', 'TNFRSF10C', 'RP11-617F23.1', 'NIBP', 'RUNX3', 'TBCC', 'HEBP2', 'GUCA1A', 'ABT1', 'CD163', 'ZNF205', 'MRC2', 'LOC730096', 'ADARB1', 'OSBPL10', 'HOXA9', 'CD2', 'VAMP2', 'SLC26A6', 'MARCO', 'PPP1R1B', 'MED1', 'IGLC3', 'BPIFB2', 'MED31', 'CLEC10A', 'GSTT1', 'IGKC', 'PGDS', 'ABCG2', 'YAP1', 'CR2', 'SYNGR3', 'FABP7', 'ANK1', 'CPA3', 'GM2A', 'BCL11A', 'KPNA2', 'GALNT3', 'GPR44', 'PTPN13', 'RNASE2', 'LTA', 'FCAR', 'KIR2DS1', 'NCALD', 'HIST1H4H', 'FAM30A', 'SERPINA3', 'ATF3', 'CCL13', 'LRP5L', 'EREG', 'LPCAT4', 'SLC18A2', 'FBP1', 'CD1C', 'AES', 'PI15', 'TRAT1', 'KIR3DS1', 'MICAL2', 'APOD', 'RRP12', 'PVALB', 'CTSK', 'DUSP2', 'SERPINA5', 'PLA2G6', 'CDK12', 'CD1E', 'MICAL3', 'MLPH', 'SLC16A7', 'ERLIN2', 'PPAPDC1B', 'CDC5L', 'ARL4C', 'ZNF528', 'IGHM', 'AL080130', 'LMAN2L', 'ATF2', 'FAM111A', 'MSL1', 'MT1E', 'CTSG', 'GRB7', 'KCNH2', 'ADM', 'PHF10', 'DTNB', 'LDB3', 'ITM2A', 'SLC15A2', 'UBE2L3', 'FABP4', 'RP1-257A7.5', 'BIRC5', 'LMO4', 'CDC7', 'RP11-110G21.2', 'SIAH1', 'PMCH', 'NLK', 'PRX', 'PARD6B', 'LIMA1', 'COCH', 'ABHD2', 'GZMB', 'SCN3A', 'TCEAL4', 'SF1', 'CD19', 'NR0B1', 'ALDH1B1', 'IL8RA', 'RP11-64B16.2', 'LCK', 'GUCY1A3', 'ELF5', 'RP11-690G19.3', 'NEIL3', 'TCC38', 'CD8A', 'QRSL1', 'CEACAM6', 'CSF2', 'EFNA3', 'HEBP1', 'TPSB2', 'FDX1', 'MPPED1', 'KIAA0125', 'C19orf6', 'NM_017616', 'MYST3', 'CEACAM3', 'SULT1C2', 'CD6', 'SYNJ1', 'IL22', 'HLA-DOB', 'SEMA4B', 'IL21R', 'PPP1R2', 'ANKRD30B', 'IL26', 'MUC3B', 'RPL19', 'MTND2P28', 'HOXA10', 'MB', 'AHI1', 'SGMS1', 'LRRC31', 'MS4A1', 'CPB1', 'PTGIS', 'GGT1', 'MMP12', 'CHI3L1', 'HIST1H1C', 'MYO15B', 'IGSF2', 'S100A12', 'ALPL', 'FUSIP1', 'NCR1', 'ZBTB18', 'FGFR2', 'RORA', 'CCR3', 'CCL17', 'IL5RA', 'GNG7', 'LRP8', 'CD72', 'VIM', 'SLC24A3', 'CENPF', 'ANP32B', 'ZFP36L2', 'SCG5', 'AMFR', 'LRRN3', 'THSD4', 'GTF3C1', 'CSF1R', 'HPSE', 'CA12', 'CARD9', 'RHOV', 'IGFBP5', 'ZEB1', 'RARRES3', 'MS4A6A', 'ANKRD30A', 'C12orf47', 'RP11-53O19.1', 'MED13L', 'ZBTB32', 'MCM3AP', 'ESR1', 'RAI14', 'CTD-2314B22.3', 'NGRN', 'THUMPD1', 'BCAT1', 'FPR1', 'SLC43A3', 'IL12RB2', 'KIR3DL1', 'TCL1A', 'TXNDC17', 'FCGR3B', 'HELLS', 'BST1', 'GATA3', 'CDC25C', 'RNU2', 'DHFR', 'IGHA1', 'HSPB8', 'PDXK', 'TSC22D3', 'MEF2C', 'STC2', 'CALB2', 'MME', 'CAPS', 'FCRL2', 'CCR9', 'PDE4B', 'LOC728210', 'EFCAB4A', 'APOL3', 'TMC6', 'CD82', 'CD70', 'PPM1H', 'CYP4F3', 'SIGLEC5', 'CIB1', 'RPL29P11', 'AREG', 'KRT23', 'CXCR6', 'ZBTB16', 'CCL1', 'BLK', 'HLA-DQA1', 'CD28', 'RPA1', 'GAGE2', 'EMP1', 'RAP1GAP', 'KLF9', 'BTG3', 'BLNK', 'DYRK3', 'PXDC1', 'KBTBD11', 'DGKI', 'PREP', 'TIMP3', 'UBD', 'IGHG1', 'IL8', 'S1PR5', 'RRAD', 'RBM3', 'LRBA', 'SNRPD1', 'CMA1', 'CLEC5A', 'SFRP1', 'SPIB', 'DEGS2', 'ZNF22', 'SCARB2', 'BCL2', 'SFRS7', 'TACSTD2', 'DSCAM-AS1', 'TIPARP', 'PEG10', 'SSFA2', 'CXCL1', 'MUC19', 'CAT', 'RP11-483P21.2', 'NR1D1', 'SLC25A12', 'C9orf156', 'MPO', 'SLC7A8', 'MSR1', 'ATP9A', 'ACACB', 'CTNS', 'RP11-96D1.10', 'AC026806.2', 'CLDN1', 'F13A1', 'C10orf10', 'TAL1', 'MGAM', 'LIME1', 'PSMD4', 'NUP107', 'ZNF91', 'CHIT1']

In [35]:
t = pd.read_csv('mart_export.txt', sep=',')

In [36]:
geneNameDF = t.iloc[:,:]

In [37]:
geneNameDF.head()

,Gene stable ID,Gene name,Gene type,Gene start (bp),Gene end (bp),Chromosome/scaffold name
0,ENSG00000283891,MIR628,miRNA,55372940,55373034,15
1,ENSG00000251931,RNU6-871P,snRNA,59450673,59450772,12
2,ENSG00000207766,MIR626,miRNA,41691585,41691678,15
3,ENSG00000275323,AC012314.7,protein_coding,54201473,54208260,CHR_HSCHR19LRC_LRC_J_CTG3_1
4,ENSG00000276678,GHRLOS,misc_RNA,10287413,10287482,3

In [38]:
geneNameDF.to_csv('geneNames.csv', sep=',',index=False)

In [39]:
#Create a python dic of geneNames and geneIDs
import csv
reader = csv.reader(open('geneNames.csv', 'r'))
IDtoName = {}
NametoID = {}
for row in reader:
    k, v = row[0], row[1]
    IDtoName[k] = v
    NametoID[v] = k

In [40]:
#Get the geneIDs of the marker genes
requiredGenesIDs = []
for i in range(len(requiredGenes)):
    if requiredGenes[i] in NametoID.keys():
        requiredGenesIDs.append(str(NametoID[requiredGenes[i]]))
    else:
        print(requiredGenes[i])

RP11-658F2.8
INDO
ARL6IP2
KAL1
RP11-697E2.7
LOC643313
EMR1
IGL
LOH11CR2A
KIAA1467
WHDC1L1
C4orf15
TRA
SMEK1
RP11-889L3.1
RP11-640M9.1
CMAH
AF107846
TM7SF4
RP11-353N4.6
IL8RB
RP5-886K2.1
ELA2
RP11
LOC339524
ADCK3
RP13-39P12.3
FPRL1
C13orf34
RP11-617F23.1
NIBP
LOC730096
PGDS
GPR44
PPAPDC1B
AL080130
RP1-257A7.5
RP11-110G21.2
IL8RA
RP11-64B16.2
RP11-690G19.3
TCC38
KIAA0125
C19orf6
NM_017616
MYST3
MUC3B
IGSF2
FUSIP1
C12orf47
RP11-53O19.1
CTD-2314B22.3
RNU2
LOC728210
EFCAB4A
GAGE2
IL8
SFRS7
RP11-483P21.2
C9orf156
RP11-96D1.10
AC026806.2

In [41]:
print (len(requiredGenesIDs))

525

In [42]:
print(len(requiredGenes))

587

In [43]:
#Filter out only those rows from both the singleCellDF and bulkCellDF that belong to a marker gene
fullSingleDF = fullSingleDF[fullSingleDF['gene_name'].isin(requiredGenes)]

In [44]:
fullSingleDF.head()

,gene_id,gene_name,gene_type,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
40,ENSG00000003436.10,TFPI,protein_coding,0.04,17.61,0.27,88.27,32.64,79.54,26.71,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,21.15,4.77,0.0
44,ENSG00000003989.12,SLC7A2,protein_coding,73.57,22.60,16.29,4.14,1.40,0.38,1.86,...,0.0,0.0,0.0,0.0,1.63,0.0,0.0,0.06,0.00,0.0
50,ENSG00000004468.8,CD38,protein_coding,0.00,19.33,0.78,16.31,111.30,0.63,0.00,...,0.0,0.0,6.1,0.0,0.00,0.0,0.0,0.24,0.00,0.0
94,ENSG00000005381.6,MPO,protein_coding,0.00,0.00,0.99,10.92,6.88,0.00,0.00,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0
99,ENSG00000005471.11,ABCB4,protein_coding,0.79,5.71,0.44,0.00,5.14,7.84,0.06,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0

In [45]:
fullSingleDF.drop(fullSingleDF.columns[[0,2]],axis=1,inplace=True)

In [46]:
fullSingleDF.shape

(550, 564)

In [47]:
fullSingleDF.head()

,gene_name,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,BC06_Pooled,BC07_Tumor,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
40,TFPI,0.04,17.61,0.27,88.27,32.64,79.54,26.71,11.88,29.65,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,21.15,4.77,0.0
44,SLC7A2,73.57,22.60,16.29,4.14,1.40,0.38,1.86,0.00,1.97,...,0.0,0.0,0.0,0.0,1.63,0.0,0.0,0.06,0.00,0.0
50,CD38,0.00,19.33,0.78,16.31,111.30,0.63,0.00,9.51,9.70,...,0.0,0.0,6.1,0.0,0.00,0.0,0.0,0.24,0.00,0.0
94,MPO,0.00,0.00,0.99,10.92,6.88,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0
99,ABCB4,0.79,5.71,0.44,0.00,5.14,7.84,0.06,0.28,2.37,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0

In [48]:
fullSingleDF = fullSingleDF.drop_duplicates(["gene_name"])

In [49]:
fullSingleDF.BC01_02

40         0.00
44        22.98
50         0.00
94         0.00
99         0.00
151        0.00
184        0.00
208        0.00
281        0.00
289        0.00
309        0.00
319        0.00
344       64.10
347        0.00
394        0.00
408        0.00
458        0.00
483        0.00
514        0.00
561        0.00
568       13.33
576        9.85
649        0.00
653        0.00
687       16.16
704       17.93
709        0.69
742        0.16
748        0.00
751        0.00
          ...
30045      4.47
30066    187.12
30240     16.61
30351      0.00
30873      2.61
34692      0.00
35997      0.00
38271      0.00
38578      0.00
38749     22.24
38976      0.00
39094      0.00
39490      4.69
39751      0.00
40011      0.00
42463    947.69
44336      0.00
44497      0.00
47239      0.00
47719      0.00
47759    158.25
48646      0.00
49418      0.00
51015     83.87
53601      0.00
53630      6.88
55029     27.38
55244      0.00
55287      0.00
57074      0.00
Name: BC01_02, Length: 546, dtype: float64

In [50]:
fullSingleDF.to_csv('temp_single_cell.txt', sep='\t',index=False)