In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import loadtxt
%matplotlib inline

In [23]:
bulkCellDF = pd.read_csv('full_healthy_bulk.txt', sep='\t')

In [24]:
singleCellDF = pd.read_csv('singleCellMatrix.txt', sep='\t')

In [25]:
#Make first row the column names for both singleCellDF and bulkCellDF
#new_header = singleCellDF.iloc[0] #grab the first row for the header
#singleCellDF = singleCellDF[1:] #take the data less the header row
#singleCellDF.columns = new_header #set the header row as the df header

In [26]:
#new_header_2 = bulkCellDF.iloc[0] #grab the first row for the header
#bulkCellDF = bulkCellDF[1:] #take the data less the header row
#bulkCellDF.columns = new_header_2 #set the header row as the df header

In [27]:
singleCellDF.head()

,gene_name,0,1,2,3,4,5,6,7,8
0,TFPI,1.465601,5.790933,4.762660,5.277150,4.375703,4.440454,4.238528,3.601634,0.042644
1,SLC7A2,0.142413,0.018092,0.395275,4.397075,0.003929,0.025619,0.270963,0.000000,0.000000
2,CD38,6.930397,0.130303,3.261198,0.998688,6.379741,0.094799,0.000000,5.967812,6.077777
3,MPO,0.627774,0.015715,0.230794,1.957678,0.010454,0.000000,0.000000,0.000000,0.000000
4,ABCB4,2.245919,0.902120,2.801765,1.062436,3.387124,0.000000,2.099132,4.152781,0.000000

In [28]:
bulkCellDF.head()

,Unnamed: 0,GTEX-1117F-2826-SM-5GZXL,GTEX-111YS-1926-SM-5GICC,GTEX-1122O-1226-SM-5H113,GTEX-117XS-1926-SM-5GICO,GTEX-117YX-1426-SM-5H12H,GTEX-1192X-2326-SM-5987X,GTEX-11DXW-0626-SM-5N9ER,GTEX-11DXY-2326-SM-5GICW,GTEX-11DXZ-1926-SM-5GZZL,...,GTEX-ZWKS-2826-SM-5NQ74,GTEX-ZXES-0826-SM-5E43C,GTEX-ZY6K-1626-SM-5GZWV,GTEX-ZYFC-0826-SM-5E44K,GTEX-ZYT6-0126-SM-5E45J,GTEX-ZYW4-0826-SM-5GIDG,GTEX-ZYWO-2326-SM-5GZY4,GTEX-ZZ64-1226-SM-5E43R,GTEX-ZZPU-0626-SM-5E43T,healthy
0,OR4F5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001968
1,OR4F29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,OR4F16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,SAMD11,0.642406,0.846530,1.296243,0.349784,1.298617,1.173224,2.732801,1.806353,1.065643,...,1.558898,0.986626,2.988975,3.047899,1.686448,2.821460,1.127609,0.225977,1.019468,1.859985
4,NOC2L,6.464367,6.400123,6.387794,5.520190,5.961856,6.359479,6.386788,5.493368,5.619234,...,5.645422,6.505231,6.911370,5.677656,5.700953,6.391541,6.296097,5.535478,6.261073,6.290511

In [29]:
bulkCellDF = bulkCellDF.rename(index=str, columns={"Unnamed: 0": "gene_name"})

In [30]:
singleCellDF.shape

(546, 10)

In [31]:
bulkCellDF.shape

(18133, 216)

In [32]:
joined_df = bulkCellDF.merge(singleCellDF, on='gene_name', how='inner')

In [33]:
joined_df.shape

(496, 225)

In [34]:
joined_df.head()

,gene_name,GTEX-1117F-2826-SM-5GZXL,GTEX-111YS-1926-SM-5GICC,GTEX-1122O-1226-SM-5H113,GTEX-117XS-1926-SM-5GICO,GTEX-117YX-1426-SM-5H12H,GTEX-1192X-2326-SM-5987X,GTEX-11DXW-0626-SM-5N9ER,GTEX-11DXY-2326-SM-5GICW,GTEX-11DXZ-1926-SM-5GZZL,...,healthy,0,1,2,3,4,5,6,7,8
0,ISG15,5.118993,4.779098,4.620557,5.647437,4.976218,5.746374,6.506874,6.152496,5.342366,...,5.924655,7.039832,5.362478,7.519771,8.319625,4.888987,4.076744,3.742145,9.266710,9.291369
1,ALPL,6.805054,5.636749,6.428022,4.736335,4.166352,5.979588,4.946837,3.986269,3.047103,...,5.956555,1.958114,0.386942,1.605853,0.065134,0.000000,0.000000,0.346110,0.015107,0.000000
2,RAP1GAP,2.822593,3.476632,3.996737,1.024318,0.062589,2.855557,3.957918,0.514156,0.763110,...,3.257774,0.080414,1.817526,0.742376,1.307429,0.011105,0.382206,0.980910,0.000000,0.000000
3,RUNX3,2.572670,2.598286,2.895521,2.951001,1.616910,3.330319,2.188603,2.582683,2.234654,...,3.202935,5.256795,1.049797,4.082762,2.017630,5.622970,0.215161,2.664813,3.190615,4.366711
4,IFI6,5.384089,6.187547,6.538909,6.794931,7.002357,6.482899,7.195496,6.814394,6.663859,...,7.093742,4.261034,6.039274,7.228453,9.434983,1.486831,4.326609,5.736099,8.842985,6.956057

In [35]:
#final_bulk_df = joined_df.loc[:,'gene_id':'sample30']
#Non-generic
final_bulk_df = joined_df.loc[:,'gene_name':'GTEX-ZZPU-0626-SM-5E43T']

In [36]:
final_bulk_df = final_bulk_df.drop_duplicates(["gene_name"])
final_bulk_df.to_csv('final1_healthy_bulk_data.txt', sep='\t',index=False)

In [37]:
#joined_df.drop(joined_df.columns[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]],axis=1,inplace=True)
#joined_df.drop(joined_df.columns[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]],axis=1,inplace=True)
#Non-generic
single_cell_df = joined_df.loc[:,'0':'8']

In [38]:
single_cell_df.insert(0, 'gene_name', joined_df.iloc[:,0])

In [39]:
single_cell_df.head()

,gene_name,0,1,2,3,4,5,6,7,8
0,ISG15,7.039832,5.362478,7.519771,8.319625,4.888987,4.076744,3.742145,9.266710,9.291369
1,ALPL,1.958114,0.386942,1.605853,0.065134,0.000000,0.000000,0.346110,0.015107,0.000000
2,RAP1GAP,0.080414,1.817526,0.742376,1.307429,0.011105,0.382206,0.980910,0.000000,0.000000
3,RUNX3,5.256795,1.049797,4.082762,2.017630,5.622970,0.215161,2.664813,3.190615,4.366711
4,IFI6,4.261034,6.039274,7.228453,9.434983,1.486831,4.326609,5.736099,8.842985,6.956057

In [40]:
single_cell_df = single_cell_df.round(8)
single_cell_df = single_cell_df.drop_duplicates(["gene_name"])

In [41]:
single_cell_df.to_csv('finalHealthy_single_cell.txt', sep='\t',index=False)

In [42]:
single_cell_df.shape

(496, 10)

In [43]:
final_bulk_df.shape

(496, 215)