In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import loadtxt
%matplotlib inline

In [12]:
#Read single Cell file
#singleCellDF = pd.read_csv('final_single_cell_data.txt', sep='\t',header=None)
singleCellDF = pd.read_csv('temp_single_cell.txt', sep='\t')

In [13]:
#Remove everything from . till end of string
singleCellDF.head()

,gene_name,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,BC06_Pooled,BC07_Tumor,...,BC11_04,BC11_07,BC11_28,BC11_43,BC11_56,BC11_69,BC11_70,BC11_78,BC11_81,BC11_88
0,TFPI,0.04,17.61,0.27,88.27,32.64,79.54,26.71,11.88,29.65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.15,4.77,0.0
1,CD38,0.00,19.33,0.78,16.31,111.30,0.63,0.00,9.51,9.70,...,0.0,0.0,6.1,0.0,0.0,0.0,0.0,0.24,0.00,0.0
2,MPO,0.00,0.00,0.99,10.92,6.88,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
3,ABCB4,0.79,5.71,0.44,0.00,5.14,7.84,0.06,0.28,2.37,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
4,TBXA2R,0.00,2.36,0.44,0.00,0.35,0.00,0.19,0.80,1.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0

In [14]:
#Make first row the column names for both singleCellDF and bulkCellDF
#new_header = singleCellDF.iloc[0] #grab the first row for the header
#singleCellDF = singleCellDF[1:] #take the data less the header row
#singleCellDF.columns = new_header #set the header row as the df header

In [15]:
#Calculate the average and take log2(TPM+1)
singleCellDF['BC_01'] = np.log(singleCellDF.iloc[:,15:41].astype(float).mean(axis=1).add(1))
singleCellDF['BC_02'] = np.log(singleCellDF.iloc[:,41:97].astype(float).mean(axis=1).add(1))
singleCellDF['BC_03'] = np.log(singleCellDF.iloc[:,97:134].astype(float).mean(axis=1).add(1))
singleCellDF['BC_03LN'] = np.log(singleCellDF.iloc[:,134:189].astype(float).mean(axis=1).add(1))
singleCellDF['BC_04'] = np.log(singleCellDF.iloc[:,189:248].astype(float).mean(axis=1).add(1))
singleCellDF['BC_05'] = np.log(singleCellDF.iloc[:,248:325].astype(float).mean(axis=1).add(1))
singleCellDF['BC_06'] = np.log(singleCellDF.iloc[:,325:350].astype(float).mean(axis=1).add(1))
singleCellDF['BC_07'] = np.log(singleCellDF.iloc[:,350:401].astype(float).mean(axis=1).add(1))
singleCellDF['BC_07LN'] = np.log(singleCellDF.iloc[:,401:454].astype(float).mean(axis=1).add(1))
singleCellDF['BC_08'] = np.log(singleCellDF.iloc[:,454:477].astype(float).mean(axis=1).add(1))
singleCellDF['BC_09'] = np.log(singleCellDF.iloc[:,477:537].astype(float).mean(axis=1).add(1))
singleCellDF['BC_10'] = np.log(singleCellDF.iloc[:,537:553].astype(float).mean(axis=1).add(1))
singleCellDF['BC_11'] = np.log(singleCellDF.iloc[:,553:564].astype(float).mean(axis=1).add(1))

In [16]:
singleCellDF.head()

,gene_name,BC01_Pooled,BC01_Tumor,BC02_Pooled,BC03_Pooled,BC03LN_Pooled,BC04_Pooled,BC05_Pooled,BC06_Pooled,BC07_Tumor,...,BC_03LN,BC_04,BC_05,BC_06,BC_07,BC_07LN,BC_08,BC_09,BC_10,BC_11
0,TFPI,0.04,17.61,0.27,88.27,32.64,79.54,26.71,11.88,29.65,...,2.930913,3.880438,3.179314,1.057790,4.544950,1.833095,0.963506,1.445113,0.000000,1.261298
1,CD38,0.00,19.33,0.78,16.31,111.30,0.63,0.00,9.51,9.70,...,4.868757,0.269898,0.000000,2.998329,1.869386,3.461665,0.343590,4.233191,0.049385,0.537556
2,MPO,0.00,0.00,0.99,10.92,6.88,0.00,0.00,0.00,0.00,...,1.663168,0.007766,0.000000,0.011138,0.470739,0.002262,0.000000,0.000000,0.000000,0.000000
3,ABCB4,0.79,5.71,0.44,0.00,5.14,7.84,0.06,0.28,2.37,...,0.259002,0.399231,1.293267,2.232892,1.614133,1.678612,0.021506,1.790481,0.000000,0.000000
4,TBXA2R,0.00,2.36,0.44,0.00,0.35,0.00,0.19,0.80,1.75,...,0.111704,0.671127,0.059004,0.000000,0.477086,0.274195,0.183046,0.000000,0.057679,0.000000

In [17]:
#Do necessary preprocessing to get the final signatureMatrixDF
finalSingleCellDF = singleCellDF.iloc[:,564:]
finalSingleCellDF.insert(0, 'gene_name', singleCellDF.iloc[:,0])

In [18]:
finalSingleCellDF.head()

,gene_name,BC_01,BC_02,BC_03,BC_03LN,BC_04,BC_05,BC_06,BC_07,BC_07LN,BC_08,BC_09,BC_10,BC_11
0,TFPI,0.018293,0.000000,4.397451,2.930913,3.880438,3.179314,1.057790,4.544950,1.833095,0.963506,1.445113,0.000000,1.261298
1,CD38,0.006517,0.035781,3.485820,4.868757,0.269898,0.000000,2.998329,1.869386,3.461665,0.343590,4.233191,0.049385,0.537556
2,MPO,0.000000,0.000000,1.545144,1.663168,0.007766,0.000000,0.011138,0.470739,0.002262,0.000000,0.000000,0.000000,0.000000
3,ABCB4,0.000000,0.362657,3.276635,0.259002,0.399231,1.293267,2.232892,1.614133,1.678612,0.021506,1.790481,0.000000,0.000000
4,TBXA2R,0.000000,0.115876,0.000000,0.111704,0.671127,0.059004,0.000000,0.477086,0.274195,0.183046,0.000000,0.057679,0.000000

In [19]:
finalSingleCellDF.shape

(419, 14)

In [20]:
#Save the finalSignature Matrix and run CIBERSORT on it
finalSingleCellDF.to_csv('singleCellMatrix.txt', sep='\t',index=False)